import 'app_state.dart';

final List<CategoryModel> newDefaultCategories = [
  CategoryModel(name: 'Sandwich', serialNumber: 1),
  CategoryModel(name: 'Grilled Sandwich', serialNumber: 2),
  CategoryModel(name: 'Pizza', serialNumber: 3),
  CategoryModel(name: 'Paneer Special', serialNumber: 4),
  CategoryModel(name: 'Kaju Special', serialNumber: 5),
  CategoryModel(name: 'Punjabi', serialNumber: 6),
  CategoryModel(name: 'Tandoori & Roti', serialNumber: 7),
  CategoryModel(name: 'Soup', serialNumber: 8),
  CategoryModel(name: 'Noodles', serialNumber: 9),
  CategoryModel(name: 'Veg. Food & Gravy', serialNumber: 10),
  CategoryModel(name: 'Rice Dish', serialNumber: 11),
  CategoryModel(name: 'Sizzlers', serialNumber: 12),
  CategoryModel(name: 'Cold Drinks', serialNumber: 13),
];

final List<MenuItem> newDefaultMenu = [
  // --- 1. Sandwich (32 items) ---
  MenuItem(id: 1, name: 'Toast Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 1),
  MenuItem(id: 2, name: 'Veg. Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 2),
  MenuItem(id: 3, name: 'Jain Veg. Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 3),
  MenuItem(id: 4, name: 'Bread Butter', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 4),
  MenuItem(id: 5, name: 'Chatni Bread Butter', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 5),
  MenuItem(id: 6, name: 'Jam Bread Butter', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 6),
  MenuItem(id: 7, name: 'Jain Veg. Toast Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 7),
  MenuItem(id: 8, name: 'Bread Butter Toast Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 8),
  MenuItem(id: 9, name: 'Chatni Toast Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 9),
  MenuItem(id: 10, name: 'Jam Toast Sandwich', price: 70, category: 'Sandwich', desc: '140 gms', serialNumber: 10),
  MenuItem(id: 11, name: 'Pizza Masala Toast Sandwich', price: 70, category: 'Sandwich', desc: '140 gms', serialNumber: 11),
  MenuItem(id: 12, name: 'Jam Veg. Sandwich', price: 60, category: 'Sandwich', desc: '140 gms', serialNumber: 12),
  MenuItem(id: 13, name: 'Aahar Sp. Sandwich', price: 90, category: 'Sandwich', desc: '160 gms', serialNumber: 13),
  MenuItem(id: 14, name: 'Veg. Cheese Sandwich', price: 90, category: 'Sandwich', desc: '160 gms', serialNumber: 14),
  MenuItem(id: 15, name: 'Bread Butter Cheese Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 15),
  MenuItem(id: 16, name: 'Jam Cheese Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 16),
  MenuItem(id: 17, name: 'Cheese Toast Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 17),
  MenuItem(id: 18, name: 'Veg. Cheese Toast Sandwich', price: 90, category: 'Sandwich', desc: '160 gms', serialNumber: 18),
  MenuItem(id: 19, name: 'Masala Cheese Toast Sandwich', price: 90, category: 'Sandwich', desc: '160 gms', serialNumber: 19),
  MenuItem(id: 20, name: 'Jam Cheese Toast Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 20),
  MenuItem(id: 21, name: 'Capsicum Cheese Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 21),
  MenuItem(id: 22, name: 'Sp. Cheese Pizza Toast Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 22),
  MenuItem(id: 23, name: 'Icey Picey Cheese Toast Sandwich', price: 120, category: 'Sandwich', desc: '170 gms', serialNumber: 23),
  MenuItem(id: 24, name: 'Cocktail Cheese Toast Sandwich', price: 110, category: 'Sandwich', desc: '150 gms', serialNumber: 24),
  MenuItem(id: 25, name: 'Pineapple Cheese Toast Sandwich', price: 100, category: 'Sandwich', desc: '150 gms', serialNumber: 25),
  MenuItem(id: 26, name: 'Garlic Cheese Toast', price: 90, category: 'Sandwich', desc: '140 gms', serialNumber: 26),
  MenuItem(id: 27, name: 'Tomato Cheese Toast', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 27),
  MenuItem(id: 28, name: 'Club Sandwich', price: 120, category: 'Sandwich', desc: '180 gms', serialNumber: 28),
  MenuItem(id: 29, name: 'Paneer Pakoda Toast Sandwich', price: 100, category: 'Sandwich', desc: '160 gms', serialNumber: 29),
  MenuItem(id: 30, name: 'Icey Picey Toast Sandwich', price: 90, category: 'Sandwich', desc: '160 gms', serialNumber: 30),
  MenuItem(id: 31, name: 'Cocktail Toast Sandwich', price: 90, category: 'Sandwich', desc: '150 gms', serialNumber: 31),
  MenuItem(id: 32, name: 'Pineapple Toast Sandwich', price: 80, category: 'Sandwich', desc: '140 gms', serialNumber: 32),

  // --- 2. Grilled Sandwich (25 items) ---
  MenuItem(id: 33, name: 'Only Cheese Grilled Sandwich', price: 200, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 33),
  MenuItem(id: 34, name: 'Mini Only Cheese Grilled Sandwich', price: 170, category: 'Grilled Sandwich', desc: '180 gms', serialNumber: 34),
  MenuItem(id: 35, name: 'Sp. Veg. Cheese Grilled Sandwich', price: 190, category: 'Grilled Sandwich', desc: '400 gms', serialNumber: 35),
  MenuItem(id: 36, name: 'Mini Sp. Veg. Cheese Grilled Sandwich', price: 160, category: 'Grilled Sandwich', desc: '280 gms', serialNumber: 36),
  MenuItem(id: 37, name: 'Pineapple Cheese Grilled Sandwich', price: 200, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 37),
  MenuItem(id: 38, name: 'Mini Pineapple Cheese Grilled Sandwich', price: 170, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 38),
  MenuItem(id: 39, name: 'Schezwan Cheese Grilled Sandwich', price: 210, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 39),
  MenuItem(id: 40, name: 'Mini Schezwan Cheese Grilled Sandwich', price: 180, category: 'Grilled Sandwich', desc: '180 gms', serialNumber: 40),
  MenuItem(id: 41, name: 'Mushroom Cheese Grilled Sandwich', price: 220, category: 'Grilled Sandwich', desc: '380 gms', serialNumber: 41),
  MenuItem(id: 42, name: 'Mini Mushroom Cheese Grilled Sandwich', price: 180, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 42),
  MenuItem(id: 43, name: 'Capsicum Onion Cheese Grilled Sandwich', price: 170, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 43),
  MenuItem(id: 44, name: 'Mini Capsicum Onion Cheese Grilled Sandwich', price: 150, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 44),
  MenuItem(id: 45, name: 'Masala Cheese Grilled Sandwich', price: 200, category: 'Grilled Sandwich', desc: '400 gms', serialNumber: 45),
  MenuItem(id: 46, name: 'Mini Masala Cheese Grilled Sandwich', price: 170, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 46),
  MenuItem(id: 47, name: 'Veg. Grilled Sandwich', price: 160, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 47),
  MenuItem(id: 48, name: 'Mini Veg. Grilled Sandwich', price: 130, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 48),
  MenuItem(id: 49, name: 'Italian Cheese Grilled Sandwich', price: 210, category: 'Grilled Sandwich', desc: '400 gms', serialNumber: 49),
  MenuItem(id: 50, name: 'Mini Italian Cheese Grilled Sandwich', price: 180, category: 'Grilled Sandwich', desc: '250 gms', serialNumber: 50),
  MenuItem(id: 51, name: 'Jam Veg. Cheese Grilled Sandwich', price: 200, category: 'Grilled Sandwich', desc: '300 gms', serialNumber: 51),
  MenuItem(id: 52, name: 'Mini Jam Veg. Cheese Grilled Sandwich', price: 180, category: 'Grilled Sandwich', desc: '180 gms', serialNumber: 52),
  MenuItem(id: 53, name: 'Veg. Corn Cheese Grilled Sandwich', price: 200, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 53),
  MenuItem(id: 54, name: 'Veg. Paneer Grilled Sandwich', price: 200, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 54),
  MenuItem(id: 55, name: 'Sp. Veg. Paneer Cheese Grilled Sandwich', price: 220, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 55),
  MenuItem(id: 56, name: 'Lumsum Cheese Grilled Sandwich', price: 220, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 56),
  MenuItem(id: 57, name: 'Chinese Grilled Sandwich', price: 210, category: 'Grilled Sandwich', desc: '350 gms', serialNumber: 57),

  // --- 3. Pizza (31 items) ---
  MenuItem(id: 58, name: 'Aahar Sp. Veg. Cheese Pizza', price: 180, category: 'Pizza', serialNumber: 58),
  MenuItem(id: 59, name: 'Mini Aahar Sp. Veg. Cheese Pizza', price: 160, category: 'Pizza', serialNumber: 59),
  MenuItem(id: 60, name: 'Veg. Cheese Pizza', price: 160, category: 'Pizza', serialNumber: 60),
  MenuItem(id: 61, name: 'Mini Veg. Cheese Pizza', price: 140, category: 'Pizza', serialNumber: 61),
  MenuItem(id: 62, name: 'Sp. Jain Veg. Cheese Pizza', price: 160, category: 'Pizza', serialNumber: 62),
  MenuItem(id: 63, name: 'Mini Sp. Jain Veg. Cheese Pizza', price: 130, category: 'Pizza', serialNumber: 63),
  MenuItem(id: 64, name: 'Italian Pizza', price: 170, category: 'Pizza', serialNumber: 64),
  MenuItem(id: 65, name: 'Mini Italian Pizza', price: 150, category: 'Pizza', serialNumber: 65),
  MenuItem(id: 66, name: 'Jam Cheese Pizza', price: 180, category: 'Pizza', serialNumber: 66),
  MenuItem(id: 67, name: 'Mini Jam Cheese Pizza', price: 150, category: 'Pizza', serialNumber: 67),
  MenuItem(id: 68, name: 'Capsicum Cheese Pizza', price: 160, category: 'Pizza', serialNumber: 68),
  MenuItem(id: 69, name: 'Mini Capsicum Cheese Pizza', price: 140, category: 'Pizza', serialNumber: 69),
  MenuItem(id: 70, name: 'Tomato Cheese Pizza', price: 150, category: 'Pizza', serialNumber: 70),
  MenuItem(id: 71, name: 'Mini Tomato Cheese Pizza', price: 130, category: 'Pizza', serialNumber: 71),
  MenuItem(id: 72, name: 'Only Cheese Pizza', price: 180, category: 'Pizza', serialNumber: 72),
  MenuItem(id: 73, name: 'Mini Only Cheese Pizza', price: 160, category: 'Pizza', serialNumber: 73),
  MenuItem(id: 74, name: 'Mushroom Cheese Pizza', price: 220, category: 'Pizza', serialNumber: 74),
  MenuItem(id: 75, name: 'Mini Mushroom Cheese Pizza', price: 190, category: 'Pizza', serialNumber: 75),
  MenuItem(id: 76, name: 'Pineapple Cheese Pizza', price: 200, category: 'Pizza', serialNumber: 76),
  MenuItem(id: 77, name: 'Mini Pineapple Cheese Pizza', price: 170, category: 'Pizza', serialNumber: 77),
  MenuItem(id: 78, name: 'Chinese Pizza', price: 180, category: 'Pizza', serialNumber: 78),
  MenuItem(id: 79, name: 'Mini Chinese Pizza', price: 150, category: 'Pizza', serialNumber: 79),
  MenuItem(id: 80, name: 'Sp. Burger', price: 110, category: 'Pizza', serialNumber: 80),
  MenuItem(id: 81, name: 'Veg Cheese Burger', price: 90, category: 'Pizza', serialNumber: 81),
  MenuItem(id: 82, name: 'Veg Burger', price: 70, category: 'Pizza', serialNumber: 82),
  MenuItem(id: 83, name: 'Sp. Hot Dog', price: 110, category: 'Pizza', serialNumber: 83),
  MenuItem(id: 84, name: 'Veg Cheese Hot Dog', price: 90, category: 'Pizza', serialNumber: 84),
  MenuItem(id: 85, name: 'Paneer Burger', price: 90, category: 'Pizza', serialNumber: 85),
  MenuItem(id: 86, name: 'Paneer Hot Dog', price: 90, category: 'Pizza', serialNumber: 86),
  MenuItem(id: 87, name: 'Corn Cheese Pizza', price: 200, category: 'Pizza', serialNumber: 87),
  MenuItem(id: 88, name: 'Baby Corn Cheese Pizza', price: 220, category: 'Pizza', serialNumber: 88),

  // --- 4. Paneer Special (13 items) ---
  MenuItem(id: 89, name: 'Paneer Lajavab', price: 220, category: 'Paneer Special', desc: '400 gms', serialNumber: 89),
  MenuItem(id: 90, name: 'Paneer Adrakhi', price: 220, category: 'Paneer Special', desc: '400 gms', serialNumber: 90),
  MenuItem(id: 91, name: 'Paneer Zafrani', price: 230, category: 'Paneer Special', desc: '400 gms', serialNumber: 91),
  MenuItem(id: 92, name: 'Paneer Hazari', price: 220, category: 'Paneer Special', desc: '400 gms', serialNumber: 92),
  MenuItem(id: 93, name: 'Paneer Balti', price: 220, category: 'Paneer Special', desc: '400 gms', serialNumber: 93),
  MenuItem(id: 94, name: 'Paneer Dahi', price: 230, category: 'Paneer Special', desc: '400 gms', serialNumber: 94),
  MenuItem(id: 95, name: 'Paneer Rajarani', price: 230, category: 'Paneer Special', desc: '400 gms', serialNumber: 95),
  MenuItem(id: 96, name: 'Paneer Tandoor', price: 240, category: 'Paneer Special', desc: '400 gms', serialNumber: 96),
  MenuItem(id: 97, name: 'Paneer Takatak', price: 230, category: 'Paneer Special', desc: '400 gms', serialNumber: 97),
  MenuItem(id: 98, name: 'Paneer Musiri', price: 240, category: 'Paneer Special', desc: '400 gms', serialNumber: 98),
  MenuItem(id: 99, name: 'Paneer Olani', price: 240, category: 'Paneer Special', desc: '400 gms', serialNumber: 99),
  MenuItem(id: 100, name: 'Paneer Chaklani', price: 260, category: 'Paneer Special', desc: '400 gms', serialNumber: 100),
  MenuItem(id: 101, name: 'Paneer Dahisodi', price: 240, category: 'Paneer Special', desc: '400 gms', serialNumber: 101),

  // --- 5. Kaju Special (6 items) ---
  MenuItem(id: 102, name: 'Sp. Kaju Tavaa Masala', price: 250, category: 'Kaju Special', desc: '400 gms', serialNumber: 102),
  MenuItem(id: 103, name: 'Sp. Kaju Kofta', price: 250, category: 'Kaju Special', desc: '400 gms', serialNumber: 103),
  MenuItem(id: 104, name: 'Kaju Malai', price: 250, category: 'Kaju Special', desc: '400 gms', serialNumber: 104),
  MenuItem(id: 105, name: 'Kaju Chatpati', price: 250, category: 'Kaju Special', desc: '400 gms', serialNumber: 105),
  MenuItem(id: 106, name: 'Kaju Balti', price: 250, category: 'Kaju Special', desc: '400 gms', serialNumber: 106),
  MenuItem(id: 107, name: 'Kaju Handi', price: 250, category: 'Kaju Special', desc: '400 gms', serialNumber: 107),

  // --- 6. Punjabi (79 items) ---
  MenuItem(id: 108, name: 'Paneer Pahadi', price: 180, category: 'Punjabi', desc: '300 gms', serialNumber: 108),
  MenuItem(id: 109, name: 'Paneer Matka', price: 180, category: 'Punjabi', desc: '300 gms', serialNumber: 109),
  MenuItem(id: 110, name: 'Paneer Sejali', price: 180, category: 'Punjabi', desc: '300 gms', serialNumber: 110),
  MenuItem(id: 111, name: 'Paneer Hungama', price: 200, category: 'Punjabi', desc: '300 gms', serialNumber: 111),
  MenuItem(id: 112, name: 'Paneer Patiyala', price: 190, category: 'Punjabi', desc: '300 gms', serialNumber: 112),
  MenuItem(id: 113, name: 'Paneer Mirch Masala', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 113),
  MenuItem(id: 114, name: 'Paneer Chana Masala', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 114),
  MenuItem(id: 115, name: 'Lollipop Masala', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 115),
  MenuItem(id: 116, name: 'Capsicum Masala', price: 150, category: 'Punjabi', desc: '300 gms', serialNumber: 116),
  MenuItem(id: 117, name: 'Veg. Hariyali', price: 140, category: 'Punjabi', desc: '300 gms', serialNumber: 117),
  MenuItem(id: 118, name: 'Veg. Hydrabadi', price: 140, category: 'Punjabi', desc: '300 gms', serialNumber: 118),
  MenuItem(id: 119, name: 'Veg. Adraki', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 119),
  MenuItem(id: 120, name: 'Veg. Amrutsari (Sweet)', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 120),
  MenuItem(id: 121, name: 'Veg. Dilli Darbar', price: 170, category: 'Punjabi', desc: '300 gms', serialNumber: 121),
  MenuItem(id: 122, name: 'Veg. Sabnam Curry (Sweet)', price: 170, category: 'Punjabi', desc: '300 gms', serialNumber: 122),
  MenuItem(id: 123, name: 'Veg. Divani Handi', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 123),
  MenuItem(id: 124, name: 'Veg. Sabnam Kofta (Sweet)', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 124),
  MenuItem(id: 125, name: 'Lajvab Kofta', price: 200, category: 'Punjabi', desc: '300 gms', serialNumber: 125),
  MenuItem(id: 126, name: 'Kaju Khoya (Sweet)', price: 180, category: 'Punjabi', desc: '300 gms', serialNumber: 126),
  MenuItem(id: 127, name: 'Veg. Tiranga', price: 220, category: 'Punjabi', desc: '300 gms', serialNumber: 127),
  MenuItem(id: 128, name: 'Mushroom Masala', price: 180, category: 'Punjabi', desc: '300 gms', serialNumber: 128),
  MenuItem(id: 129, name: 'Stuff Tometo', price: 140, category: 'Punjabi', desc: '300 gms', serialNumber: 129),
  MenuItem(id: 130, name: 'Dum Aloo', price: 140, category: 'Punjabi', desc: '300 gms', serialNumber: 130),
  MenuItem(id: 131, name: 'Dum Aloo Kashmiri', price: 150, category: 'Punjabi', desc: '300 gms', serialNumber: 131),
  MenuItem(id: 132, name: 'Jeera Aloo', price: 110, category: 'Punjabi', desc: '300 gms', serialNumber: 132),
  MenuItem(id: 133, name: 'Tometo Batata', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 133),
  MenuItem(id: 134, name: 'Papad Roll Masala', price: 160, category: 'Punjabi', desc: '300 gms', serialNumber: 134),
  MenuItem(id: 135, name: 'Bengan Masala', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 135),
  MenuItem(id: 136, name: 'Bengan Bhatta', price: 130, category: 'Punjabi', desc: '300 gms', serialNumber: 136),
  MenuItem(id: 137, name: 'Dal Fry', price: 100, category: 'Punjabi', desc: '300 gms', serialNumber: 137),
  MenuItem(id: 138, name: 'Butter Dal Fry', price: 130, category: 'Punjabi', desc: '300 gms', serialNumber: 138),
  MenuItem(id: 139, name: 'Dal Tadka', price: 130, category: 'Punjabi', desc: '300 gms', serialNumber: 139),
  MenuItem(id: 140, name: 'Palak Mutter', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 140),
  MenuItem(id: 141, name: 'Aloo Palak', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 141),
  MenuItem(id: 142, name: 'Chana Masala', price: 130, category: 'Punjabi', desc: '300 gms', serialNumber: 142),
  MenuItem(id: 143, name: 'Alu Gobi', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 143),
  MenuItem(id: 144, name: 'Alu Mutter', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 144),
  MenuItem(id: 145, name: 'Mix Veg.', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 145),
  MenuItem(id: 146, name: 'Veg. Kolhapuri', price: 140, category: 'Punjabi', desc: '300 gms', serialNumber: 146),
  MenuItem(id: 147, name: 'Veg. Makhanwala', price: 150, category: 'Punjabi', desc: '300 gms', serialNumber: 147),
  MenuItem(id: 148, name: 'Veg. Jaypuri', price: 140, category: 'Punjabi', desc: '300 gms', serialNumber: 148),
  MenuItem(id: 149, name: 'Palak Masala', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 149),
  MenuItem(id: 150, name: 'Bhindi Fry', price: 120, category: 'Punjabi', desc: '300 gms', serialNumber: 150),
  MenuItem(id: 151, name: 'Bhindi Masala', price: 120, category: 'Punjabi', desc: '350 gms', serialNumber: 151),
  MenuItem(id: 152, name: 'Punjabi Thali', price: 160, category: 'Punjabi', desc: '350 gms', serialNumber: 152),
  MenuItem(id: 153, name: 'Aahar Special', price: 170, category: 'Punjabi', desc: '350 gms', serialNumber: 153),
  MenuItem(id: 154, name: 'Veg. Handi', price: 120, category: 'Punjabi', desc: '350 gms', serialNumber: 154),
  MenuItem(id: 155, name: 'Veg. Kadai', price: 120, category: 'Punjabi', desc: '350 gms', serialNumber: 155),
  MenuItem(id: 156, name: 'Veg. Angara', price: 180, category: 'Punjabi', desc: '350 gms', serialNumber: 156),
  MenuItem(id: 157, name: 'Veg. Tufani', price: 140, category: 'Punjabi', desc: '350 gms', serialNumber: 157),
  MenuItem(id: 158, name: 'Paneer Anguri', price: 220, category: 'Punjabi', desc: '350 gms', serialNumber: 158),
  MenuItem(id: 159, name: 'Cheese Anguri', price: 220, category: 'Punjabi', desc: '350 gms', serialNumber: 159),
  MenuItem(id: 160, name: 'Cheese Butter Masala', price: 210, category: 'Punjabi', desc: '350 gms', serialNumber: 160),
  MenuItem(id: 161, name: 'Paneer Angara', price: 210, category: 'Punjabi', desc: '350 gms', serialNumber: 161),
  MenuItem(id: 162, name: 'Paneer Chatpati', price: 180, category: 'Punjabi', desc: '350 gms', serialNumber: 162),
  MenuItem(id: 163, name: 'Paneer Jodhpuri', price: 160, category: 'Punjabi', desc: '350 gms', serialNumber: 163),
  MenuItem(id: 164, name: 'Panner Badsahi', price: 170, category: 'Punjabi', desc: '350 gms', serialNumber: 164),
  MenuItem(id: 165, name: 'Panner Kolhapuri', price: 160, category: 'Punjabi', desc: '350 gms', serialNumber: 165),
  MenuItem(id: 166, name: 'Paneer Kadai', price: 150, category: 'Punjabi', desc: '350 gms', serialNumber: 166),
  MenuItem(id: 167, name: 'Paneer Tawa', price: 190, category: 'Punjabi', desc: '350 gms', serialNumber: 167),
  MenuItem(id: 168, name: 'Paneer Butter Masala', price: 150, category: 'Punjabi', desc: '350 gms', serialNumber: 168),
  MenuItem(id: 169, name: 'Paneer Tikka Masala', price: 150, category: 'Punjabi', desc: '350 gms', serialNumber: 169),
  MenuItem(id: 170, name: 'Paneer Bhurji', price: 170, category: 'Punjabi', desc: '350 gms', serialNumber: 170),
  MenuItem(id: 171, name: 'Paneer Mutter', price: 150, category: 'Punjabi', desc: '350 gms', serialNumber: 171),
  MenuItem(id: 172, name: 'Paneer Toofani', price: 160, category: 'Punjabi', desc: '350 gms', serialNumber: 172),
  MenuItem(id: 173, name: 'Paneer Handi', price: 140, category: 'Punjabi', desc: '350 gms', serialNumber: 173),
  MenuItem(id: 174, name: 'Paneer Masala', price: 160, category: 'Punjabi', desc: '350 gms', serialNumber: 174),
  MenuItem(id: 175, name: 'Paneer Palak', price: 150, category: 'Punjabi', desc: '350 gms', serialNumber: 175),
  MenuItem(id: 176, name: 'Paneer Kurma', price: 160, category: 'Punjabi', desc: '350 gms', serialNumber: 176),
  MenuItem(id: 177, name: 'Paneer Pasanda', price: 240, category: 'Punjabi', desc: '400 gms', serialNumber: 177),
  MenuItem(id: 178, name: 'Sahi Paneer', price: 160, category: 'Punjabi', desc: '400 gms', serialNumber: 178),
  MenuItem(id: 179, name: 'Paneer Express', price: 240, category: 'Punjabi', desc: '400 gms', serialNumber: 179),
  MenuItem(id: 180, name: 'Aahar Special Kofta (Sweet)', price: 220, category: 'Punjabi', desc: '400 gms', serialNumber: 180),
  MenuItem(id: 181, name: 'Aahar Special Malai Kofta (Spicy)', price: 190, category: 'Punjabi', desc: '400 gms', serialNumber: 181),
  MenuItem(id: 182, name: 'Paneer Kofta', price: 200, category: 'Punjabi', desc: '400 gms', serialNumber: 182),
  MenuItem(id: 183, name: 'Paneer Kaju', price: 180, category: 'Punjabi', desc: '400 gms', serialNumber: 183),
  MenuItem(id: 184, name: 'Veg. Kofta', price: 160, category: 'Punjabi', desc: '400 gms', serialNumber: 184),
  MenuItem(id: 185, name: 'Navratna Kurma (Sweet)', price: 170, category: 'Punjabi', desc: '400 gms', serialNumber: 185),
  MenuItem(id: 186, name: 'Veg. Kurma', price: 140, category: 'Punjabi', desc: '400 gms', serialNumber: 186),
  MenuItem(id: 187, name: 'Kaju Kari', price: 180, category: 'Punjabi', desc: '400 gms', serialNumber: 187),
  MenuItem(id: 188, name: 'Kaju Masala', price: 180, category: 'Punjabi', desc: '400 gms', serialNumber: 188),
  MenuItem(id: 189, name: 'Paneer Jvala', price: 210, category: 'Punjabi', desc: '400 gms', serialNumber: 189),
  MenuItem(id: 190, name: 'Paneer Bullet (Punjabi)', price: 220, category: 'Punjabi', desc: '400 gms', serialNumber: 190),

  // --- 7. Tandoori & Roti (27 items) ---
  MenuItem(id: 191, name: 'Tandoori Roti', price: 20, category: 'Tandoori & Roti', desc: '60 gms', serialNumber: 191),
  MenuItem(id: 192, name: 'Fat Spread Roti', price: 25, category: 'Tandoori & Roti', desc: '60 gms', serialNumber: 192),
  MenuItem(id: 193, name: 'Tava Amul Butter Roti', price: 25, category: 'Tandoori & Roti', desc: '60 gms', serialNumber: 193),
  MenuItem(id: 194, name: 'Amul Butter Roti', price: 30, category: 'Tandoori & Roti', desc: '60 gms', serialNumber: 194),
  MenuItem(id: 195, name: 'Fat Spread Parotha', price: 50, category: 'Tandoori & Roti', desc: '80 gms', serialNumber: 195),
  MenuItem(id: 196, name: 'Sada Parotha', price: 40, category: 'Tandoori & Roti', desc: '80 gms', serialNumber: 196),
  MenuItem(id: 197, name: 'Fat Spread Nan', price: 50, category: 'Tandoori & Roti', desc: '100 gms', serialNumber: 197),
  MenuItem(id: 198, name: 'Sada Nan', price: 40, category: 'Tandoori & Roti', desc: '100 gms', serialNumber: 198),
  MenuItem(id: 199, name: 'Kashmiri Nan', price: 70, category: 'Tandoori & Roti', desc: '120 gms', serialNumber: 199),
  MenuItem(id: 200, name: 'Masala Parotha', price: 70, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 200),
  MenuItem(id: 201, name: 'Stuff Parotha', price: 70, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 201),
  MenuItem(id: 202, name: 'Masala Kulcha', price: 70, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 202),
  MenuItem(id: 203, name: 'Sada Kulcha', price: 50, category: 'Tandoori & Roti', desc: '100 gms', serialNumber: 203),
  MenuItem(id: 204, name: 'Tava Roti', price: 15, category: 'Tandoori & Roti', desc: '30 gms', serialNumber: 204),
  MenuItem(id: 205, name: 'Tava Roti Fat Spread', price: 20, category: 'Tandoori & Roti', desc: '30 gms', serialNumber: 205),
  MenuItem(id: 206, name: 'Paneer Parotha', price: 80, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 206),
  MenuItem(id: 207, name: 'Paneer Nan', price: 80, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 207),
  MenuItem(id: 208, name: 'Onion Nan', price: 60, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 208),
  MenuItem(id: 209, name: 'Cheese Nan', price: 90, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 209),
  MenuItem(id: 210, name: 'Garlic Nan', price: 70, category: 'Tandoori & Roti', desc: '100 gms', serialNumber: 210),
  MenuItem(id: 211, name: 'Garlic Cheeses', price: 100, category: 'Tandoori & Roti', desc: '140 gms', serialNumber: 211),
  MenuItem(id: 212, name: 'Rosted Papad', price: 20, category: 'Tandoori & Roti', serialNumber: 212),
  MenuItem(id: 213, name: 'Fry Papad', price: 30, category: 'Tandoori & Roti', serialNumber: 213),
  MenuItem(id: 214, name: 'Masala Papad', price: 40, category: 'Tandoori & Roti', serialNumber: 214),
  MenuItem(id: 215, name: 'Butter Milk', price: 25, category: 'Tandoori & Roti', serialNumber: 215),
  MenuItem(id: 216, name: 'Green Salad', price: 80, category: 'Tandoori & Roti', serialNumber: 216),
  MenuItem(id: 217, name: 'Finger Chips', price: 100, category: 'Tandoori & Roti', serialNumber: 217),

  // --- 8. Soup (12 items) ---
  MenuItem(id: 218, name: 'Tomato Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 218),
  MenuItem(id: 219, name: 'Hot & Sour Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 219),
  MenuItem(id: 220, name: 'Veg. Manchow Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 220),
  MenuItem(id: 221, name: 'Sweet Corn Veg. Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 221),
  MenuItem(id: 222, name: 'Sweet Corn Plain Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 222),
  MenuItem(id: 223, name: 'Mushroom Soup', price: 90, category: 'Soup', desc: '350 gms', serialNumber: 223),
  MenuItem(id: 224, name: 'Ministrone Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 224),
  MenuItem(id: 225, name: 'Veg. Clear Soup', price: 70, category: 'Soup', desc: '350 gms', serialNumber: 225),
  MenuItem(id: 226, name: 'Green Peas Soup', price: 70, category: 'Soup', desc: '350 gms', serialNumber: 226),
  MenuItem(id: 227, name: 'Veg Noodles Soup', price: 80, category: 'Soup', desc: '350 gms', serialNumber: 227),
  MenuItem(id: 228, name: 'Royal Veg. Soup', price: 90, category: 'Soup', desc: '350 gms', serialNumber: 228),
  MenuItem(id: 229, name: 'Cocktail Soup', price: 90, category: 'Soup', desc: '350 gms', serialNumber: 229),

  // --- 9. Noodles (18 items) ---
  MenuItem(id: 230, name: 'Bombay Bhel', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 230),
  MenuItem(id: 231, name: 'Aaisi paisi Noodles', price: 170, category: 'Noodles', desc: '350 gms', serialNumber: 231),
  MenuItem(id: 232, name: 'Hakka Noodles', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 232),
  MenuItem(id: 233, name: 'Singapuri Noodles', price: 160, category: 'Noodles', desc: '350 gms', serialNumber: 233),
  MenuItem(id: 234, name: 'Veg. Rice & Noodles', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 234),
  MenuItem(id: 235, name: 'Schwan Noodles', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 235),
  MenuItem(id: 236, name: 'Fried Noodles', price: 170, category: 'Noodles', desc: '350 gms', serialNumber: 236),
  MenuItem(id: 237, name: 'Combination Noodles', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 237),
  MenuItem(id: 238, name: 'Mashroom Noodles', price: 160, category: 'Noodles', desc: '350 gms', serialNumber: 238),
  MenuItem(id: 239, name: 'Tripple\'s Schzwan Noodles', price: 200, category: 'Noodles', desc: '400 gms', serialNumber: 239),
  MenuItem(id: 240, name: 'American Chopsy', price: 160, category: 'Noodles', desc: '350 gms', serialNumber: 240),
  MenuItem(id: 241, name: 'Mashroom Chopsy', price: 170, category: 'Noodles', desc: '350 gms', serialNumber: 241),
  MenuItem(id: 242, name: 'Chinese Bhel', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 242),
  MenuItem(id: 243, name: 'Garlic Chawmin (Liquid)', price: 160, category: 'Noodles', desc: '350 gms', serialNumber: 243),
  MenuItem(id: 244, name: 'Garlic Chawmin (Dry)', price: 160, category: 'Noodles', desc: '350 gms', serialNumber: 244),
  MenuItem(id: 245, name: 'Veg. Chawmin (Liquid)', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 245),
  MenuItem(id: 246, name: 'Veg. Chawmin (Dry)', price: 150, category: 'Noodles', desc: '350 gms', serialNumber: 246),
  MenuItem(id: 247, name: 'Huanan Noodles', price: 200, category: 'Noodles', desc: '350 gms', serialNumber: 247),

  // --- 10. Veg. Food & Gravy (25 items) ---
  MenuItem(id: 248, name: 'Paneer Bullet', price: 220, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 248),
  MenuItem(id: 249, name: 'Paneer Schzwen Roll', price: 240, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 249),
  MenuItem(id: 250, name: 'Veg. Krivsi', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 250),
  MenuItem(id: 251, name: 'Mashroom Roll', price: 220, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 251),
  MenuItem(id: 252, name: 'Veg. Manchurian (Liquid)', price: 160, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 252),
  MenuItem(id: 253, name: 'Veg. Manchurian (Dry)', price: 160, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 253),
  MenuItem(id: 254, name: 'Mashroom Manchurian (Liquid)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 254),
  MenuItem(id: 255, name: 'Baby Corn Manchurian (Dry)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 255),
  MenuItem(id: 256, name: 'Baby Corn Manchurian (Liquid)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 256),
  MenuItem(id: 257, name: 'Baby Corn Chilli (Dry)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 257),
  MenuItem(id: 258, name: 'Paneer Manchurian (Dry)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 258),
  MenuItem(id: 259, name: 'Paneer Manchurian (Liquid)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 259),
  MenuItem(id: 260, name: 'Paneer Chilli (Dry)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 260),
  MenuItem(id: 261, name: 'Paneer Chilli (Liquid)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 261),
  MenuItem(id: 262, name: 'Paneer mamtal (Dry)', price: 250, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 262),
  MenuItem(id: 263, name: 'Paneer \'65 (Dry)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 263),
  MenuItem(id: 264, name: 'Paneer \'65 (Liquid)', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 264),
  MenuItem(id: 265, name: 'Cocktail (Dry)', price: 180, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 265),
  MenuItem(id: 266, name: 'Cocktail (Liquid)', price: 180, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 266),
  MenuItem(id: 267, name: 'Veg. Chilli (Dry)', price: 170, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 267),
  MenuItem(id: 268, name: 'Veg. Chilli (Liquid)', price: 170, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 268),
  MenuItem(id: 269, name: 'Veg. \'65 (Dry)', price: 180, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 269),
  MenuItem(id: 270, name: 'Veg. \'65 (Liquid)', price: 180, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 270),
  MenuItem(id: 271, name: 'Potato Chilli', price: 180, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 271),
  MenuItem(id: 272, name: 'Veg. Lollipop', price: 200, category: 'Veg. Food & Gravy', desc: '300 gms', serialNumber: 272),

  // --- 11. Rice Dish (30 items) ---
  MenuItem(id: 273, name: 'Huanan Rice', price: 200, category: 'Rice Dish', desc: '450 gms', serialNumber: 273),
  MenuItem(id: 274, name: 'Hongkong Rice', price: 200, category: 'Rice Dish', desc: '450 gms', serialNumber: 274),
  MenuItem(id: 275, name: 'Aahar Sp. Rice', price: 220, category: 'Rice Dish', desc: '450 gms', serialNumber: 275),
  MenuItem(id: 276, name: 'Veg. Fried Rice', price: 150, category: 'Rice Dish', desc: '300 gms', serialNumber: 276),
  MenuItem(id: 277, name: 'Mix Veg. Fried Rice', price: 150, category: 'Rice Dish', desc: '300 gms', serialNumber: 277),
  MenuItem(id: 278, name: 'Veg. Ginger Fried Rice', price: 150, category: 'Rice Dish', desc: '300 gms', serialNumber: 278),
  MenuItem(id: 279, name: 'Garlic Fried Rice', price: 170, category: 'Rice Dish', desc: '300 gms', serialNumber: 279),
  MenuItem(id: 280, name: 'Combination Rice', price: 160, category: 'Rice Dish', desc: '300 gms', serialNumber: 280),
  MenuItem(id: 281, name: 'Mashroom Fried Rice', price: 190, category: 'Rice Dish', desc: '300 gms', serialNumber: 281),
  MenuItem(id: 282, name: 'Schezwan Fried Rice', price: 160, category: 'Rice Dish', desc: '300 gms', serialNumber: 282),
  MenuItem(id: 283, name: 'Tripple Schezwan Rice', price: 200, category: 'Rice Dish', desc: '450 gms', serialNumber: 283),
  MenuItem(id: 284, name: 'Singapoori Fried Rice', price: 160, category: 'Rice Dish', desc: '300 gms', serialNumber: 284),
  MenuItem(id: 285, name: 'Chinese Veg. Pulao', price: 150, category: 'Rice Dish', desc: '300 gms', serialNumber: 285),
  MenuItem(id: 286, name: 'Paneer Pulao', price: 200, category: 'Rice Dish', desc: '350 gms', serialNumber: 286),
  MenuItem(id: 287, name: 'Cheese Pulao', price: 220, category: 'Rice Dish', desc: '350 gms', serialNumber: 287),
  MenuItem(id: 288, name: 'Punjabi Veg. Pulao', price: 160, category: 'Rice Dish', desc: '350 gms', serialNumber: 288),
  MenuItem(id: 289, name: 'Veg. Kashmiri Pulao', price: 180, category: 'Rice Dish', desc: '400 gms', serialNumber: 289),
  MenuItem(id: 290, name: 'Green Peas Pulao', price: 150, category: 'Rice Dish', desc: '300 gms', serialNumber: 290),
  MenuItem(id: 291, name: 'Veg. Biryani', price: 160, category: 'Rice Dish', desc: '450 gms', serialNumber: 291),
  MenuItem(id: 292, name: 'Hydrabadi Biryani', price: 160, category: 'Rice Dish', desc: '450 gms', serialNumber: 292),
  MenuItem(id: 293, name: 'Jira Rice', price: 110, category: 'Rice Dish', desc: '300 gms', serialNumber: 293),
  MenuItem(id: 294, name: 'Plain Rice', price: 90, category: 'Rice Dish', desc: '300 gms', serialNumber: 294),
  MenuItem(id: 295, name: 'Masala Rice', price: 160, category: 'Rice Dish', desc: '300 gms', serialNumber: 295),
  MenuItem(id: 296, name: 'Half Jira Rice', price: 80, category: 'Rice Dish', desc: '200 gms', serialNumber: 296),
  MenuItem(id: 297, name: 'Half Plain Rice', price: 70, category: 'Rice Dish', desc: '200 gms', serialNumber: 297),
  MenuItem(id: 298, name: 'Half Masala Rice', price: 110, category: 'Rice Dish', desc: '200 gms', serialNumber: 298),
  MenuItem(id: 299, name: 'Veg. Rayta', price: 80, category: 'Rice Dish', desc: '150 gms', serialNumber: 299),
  MenuItem(id: 300, name: 'Kashmiri Rayta', price: 120, category: 'Rice Dish', desc: '150 gms', serialNumber: 300),
  MenuItem(id: 301, name: 'Pineapple Rayta', price: 100, category: 'Rice Dish', desc: '150 gms', serialNumber: 301),
  MenuItem(id: 302, name: 'Bundi Rayta', price: 90, category: 'Rice Dish', desc: '150 gms', serialNumber: 302),

  // --- 12. Sizzlers (11 items + 4 variations = 15 items) ---
  MenuItem(id: 303, name: 'Veg. Sizzlers', price: 250, category: 'Sizzlers', desc: '500 gms', serialNumber: 303),
  MenuItem(id: 304, name: 'Mix Veg. Sizzlers', price: 250, category: 'Sizzlers', desc: '500 gms', serialNumber: 304),
  MenuItem(id: 305, name: 'Combination Sizzlers', price: 250, category: 'Sizzlers', desc: '500 gms', serialNumber: 305),
  MenuItem(id: 306, name: 'Mix Grill Sizzlers', price: 250, category: 'Sizzlers', desc: '500 gms', serialNumber: 306),
  MenuItem(id: 307, name: 'Chinese Sizzlers', price: 250, category: 'Sizzlers', desc: '500 gms', serialNumber: 307),
  MenuItem(id: 308, name: 'Garlic Ball (Dry)', price: 160, category: 'Sizzlers', desc: '300 gms', serialNumber: 308),
  MenuItem(id: 309, name: 'Garlic Ball (Liquid)', price: 160, category: 'Sizzlers', desc: '300 gms', serialNumber: 309),
  MenuItem(id: 310, name: 'Ginjer Ball (Dry)', price: 160, category: 'Sizzlers', desc: '300 gms', serialNumber: 310),
  MenuItem(id: 311, name: 'Ginjer Ball (Liquid)', price: 160, category: 'Sizzlers', desc: '300 gms', serialNumber: 311),
  MenuItem(id: 312, name: 'Veg. Cheese Ball (Dry)', price: 180, category: 'Sizzlers', desc: '300 gms', serialNumber: 312),
  MenuItem(id: 313, name: 'Veg. Cheese Ball (Liquid)', price: 180, category: 'Sizzlers', desc: '300 gms', serialNumber: 313),
  MenuItem(id: 314, name: 'Veg. Spring Roll', price: 200, category: 'Sizzlers', desc: '300 gms', serialNumber: 314),
  MenuItem(id: 315, name: 'Hara Bhara Kabab', price: 200, category: 'Sizzlers', desc: '200 gms', serialNumber: 315),
  MenuItem(id: 316, name: 'Schzwan Ball (Dry)', price: 170, category: 'Sizzlers', desc: '300 gms', serialNumber: 316),
  MenuItem(id: 317, name: 'Schzwan Ball (Liquid)', price: 170, category: 'Sizzlers', desc: '300 gms', serialNumber: 317),

  // --- 13. Cold Drinks (5 items) ---
  MenuItem(id: 318, name: 'Soft Drink (300 ml.)', price: 20, category: 'Cold Drinks', desc: '300 ml', serialNumber: 318),
  MenuItem(id: 319, name: 'Soft Drink (1.5 Lit.)', price: 70, category: 'Cold Drinks', desc: '1.5 Lit', serialNumber: 319),
  MenuItem(id: 320, name: 'Soft Drink (2 Lit.)', price: 90, category: 'Cold Drinks', desc: '2 Lit', serialNumber: 320),
  MenuItem(id: 321, name: 'Soda', price: 20, category: 'Cold Drinks', desc: 'Bottle', serialNumber: 321),
  MenuItem(id: 322, name: 'Min. Water', price: 20, category: 'Cold Drinks', desc: 'Bottle', serialNumber: 322),
];
