import 'app_state.dart';

final List<CategoryModel> newDefaultCategories = [
  CategoryModel(name: "SANDWICH", serialNumber: 1),
  CategoryModel(name: "GRILLED SANDWICH", serialNumber: 2),
  CategoryModel(name: "PIZZA", serialNumber: 3),
  CategoryModel(name: "BURGER", serialNumber: 4),
  CategoryModel(name: "HOT DOG", serialNumber: 5),
  CategoryModel(name: "PANEER SPECIAL", serialNumber: 6),
  CategoryModel(name: "KAJU SPECIAL", serialNumber: 7),
  CategoryModel(name: "PUNJABI", serialNumber: 8),
  CategoryModel(name: "TANDOORI", serialNumber: 9),
  CategoryModel(name: "PAPAD & SALAD", serialNumber: 10),
  CategoryModel(name: "SOUP", serialNumber: 11),
  CategoryModel(name: "NOODLES", serialNumber: 12),
  CategoryModel(name: "VEG. FOOD & GRAVY", serialNumber: 13),
  CategoryModel(name: "RICE DISH", serialNumber: 14),
  CategoryModel(name: "SIZZLERS", serialNumber: 15),
  CategoryModel(name: "COLD DRINKS", serialNumber: 16),
];

final List<MenuItem> newDefaultMenu = [
  // SANDWICH
  MenuItem(id: 1001, name: "Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 1),
  MenuItem(id: 1002, name: "Veg. Sandwich", price: 60, category: "SANDWICH", serialNumber: 2),
  MenuItem(id: 1003, name: "Jain Veg. Sandwich", price: 60, category: "SANDWICH", serialNumber: 3),
  MenuItem(id: 1004, name: "Bread Butter", price: 60, category: "SANDWICH", serialNumber: 4),
  MenuItem(id: 1005, name: "Chatni Bread Butter", price: 60, category: "SANDWICH", serialNumber: 5),
  MenuItem(id: 1006, name: "Jam Bread Butter", price: 60, category: "SANDWICH", serialNumber: 6),
  MenuItem(id: 1007, name: "Jain Veg. Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 7),
  MenuItem(id: 1008, name: "Bread Butter Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 8),
  MenuItem(id: 1009, name: "Chatni Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 9),
  MenuItem(id: 1010, name: "Jam Toast Sandwich", price: 70, category: "SANDWICH", serialNumber: 10),
  MenuItem(id: 1011, name: "Pizza Masala Toast Sandwich", price: 70, category: "SANDWICH", serialNumber: 11),
  MenuItem(id: 1012, name: "Jam Veg. Sandwich", price: 60, category: "SANDWICH", serialNumber: 12),
  MenuItem(id: 1013, name: "Aahar Sp. Sandwich", price: 90, category: "SANDWICH", serialNumber: 13),
  MenuItem(id: 1014, name: "Veg. Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 14),
  MenuItem(id: 1015, name: "Bread Butter Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 15),
  MenuItem(id: 1016, name: "Jam Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 16),
  MenuItem(id: 1017, name: "Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 17),
  MenuItem(id: 1018, name: "Veg. Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 18),
  MenuItem(id: 1019, name: "Masala Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 19),
  MenuItem(id: 1020, name: "Jam Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 20),
  MenuItem(id: 1021, name: "Capsicum Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 21),
  MenuItem(id: 1022, name: "Sp. Cheese Pizza Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 22),
  MenuItem(id: 1023, name: "Icey Picey Cheese Toast Sandwich", price: 120, category: "SANDWICH", serialNumber: 23),
  MenuItem(id: 1024, name: "Cocktail Cheese Toast Sandwich", price: 110, category: "SANDWICH", serialNumber: 24),
  MenuItem(id: 1025, name: "Pineapple Cheese Toast Sandwich", price: 100, category: "SANDWICH", serialNumber: 25),
  MenuItem(id: 1026, name: "Garlic Cheese Toast", price: 90, category: "SANDWICH", serialNumber: 26),
  MenuItem(id: 1027, name: "Tometo Cheese Toast", price: 90, category: "SANDWICH", serialNumber: 27),
  MenuItem(id: 1028, name: "Club Sandwich", price: 120, category: "SANDWICH", serialNumber: 28),
  MenuItem(id: 1029, name: "Paneer Pakoda Toast Sandwich", price: 100, category: "SANDWICH", serialNumber: 29),
  MenuItem(id: 1030, name: "Icey Picey Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 30),
  MenuItem(id: 1031, name: "Cocktail Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 31),
  MenuItem(id: 1032, name: "Pineapple Toast Sandwich", price: 80, category: "SANDWICH", serialNumber: 32),

  // GRILLED SANDWICH
  MenuItem(id: 2001, name: "Only Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 33),
  MenuItem(id: 2002, name: "Mini Only Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 34),
  MenuItem(id: 2003, name: "Sp. Veg. Cheese Grilled Sandwich", price: 190, category: "GRILLED SANDWICH", serialNumber: 35),
  MenuItem(id: 2004, name: "Mini Sp. Veg. Cheese Grilled Sandwich", price: 160, category: "GRILLED SANDWICH", serialNumber: 36),
  MenuItem(id: 2005, name: "Pineapple Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 37),
  MenuItem(id: 2006, name: "Mini Pineapple Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 38),
  MenuItem(id: 2007, name: "Schezwan Cheese Grilled Sandwich", price: 210, category: "GRILLED SANDWICH", serialNumber: 39),
  MenuItem(id: 2008, name: "Mini Schezwan Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 40),
  MenuItem(id: 2009, name: "Mushroom Cheese Grilled Sandwich", price: 220, category: "GRILLED SANDWICH", serialNumber: 41),
  MenuItem(id: 2010, name: "Mini Mushroom Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 42),
  MenuItem(id: 2011, name: "Capsicum Onion Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 43),
  MenuItem(id: 2012, name: "Mini Capsicum Onion Cheese Grilled Sandwich", price: 150, category: "GRILLED SANDWICH", serialNumber: 44),
  MenuItem(id: 2013, name: "Masala Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 45),
  MenuItem(id: 2014, name: "Mini Masala Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 46),
  MenuItem(id: 2015, name: "Veg. Grilled Sandwich", price: 160, category: "GRILLED SANDWICH", serialNumber: 47),
  MenuItem(id: 2016, name: "Mini Veg. Grilled Sandwich", price: 130, category: "GRILLED SANDWICH", serialNumber: 48),
  MenuItem(id: 2017, name: "Italian Cheese Grilled Sandwich", price: 210, category: "GRILLED SANDWICH", serialNumber: 49),
  MenuItem(id: 2018, name: "Mini Italian Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 50),
  MenuItem(id: 2019, name: "Jam Veg. Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 51),
  MenuItem(id: 2020, name: "Mini Jam Veg. Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 52),
  MenuItem(id: 2021, name: "Veg. Corn Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 53),
  MenuItem(id: 2022, name: "Veg. Paneer Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 54),
  MenuItem(id: 2023, name: "Sp. Veg. Paneer Cheese Grilled Sandwich", price: 220, category: "GRILLED SANDWICH", serialNumber: 55),
  MenuItem(id: 2024, name: "Lumsum Cheese Grilled Sandwich", price: 220, category: "GRILLED SANDWICH", serialNumber: 56),
  MenuItem(id: 2025, name: "Chinese Grilled Sandwich", price: 210, category: "GRILLED SANDWICH", serialNumber: 57),

  // PIZZA
  MenuItem(id: 3001, name: "Aahar Sp. Veg. Cheese Pizza", price: 180, category: "PIZZA", serialNumber: 58),
  MenuItem(id: 3002, name: "Mini Aahar Sp. Veg. Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 59),
  MenuItem(id: 3003, name: "Veg. Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 60),
  MenuItem(id: 3004, name: "Mini Veg. Cheese Pizza", price: 140, category: "PIZZA", serialNumber: 61),
  MenuItem(id: 3005, name: "Sp. Jain Veg. Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 62),
  MenuItem(id: 3006, name: "Mini Sp. Jain Veg. Cheese Pizza", price: 130, category: "PIZZA", serialNumber: 63),
  MenuItem(id: 3007, name: "Italian Pizza", price: 170, category: "PIZZA", serialNumber: 64),
  MenuItem(id: 3008, name: "Mini Italian Pizza", price: 150, category: "PIZZA", serialNumber: 65),
  MenuItem(id: 3009, name: "Jam Cheese Pizza", price: 180, category: "PIZZA", serialNumber: 66),
  MenuItem(id: 3010, name: "Mini Jam Cheese Pizza", price: 150, category: "PIZZA", serialNumber: 67),
  MenuItem(id: 3011, name: "Capsicum Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 68),
  MenuItem(id: 3012, name: "Mini Capsicum Cheese Pizza", price: 140, category: "PIZZA", serialNumber: 69),
  MenuItem(id: 3013, name: "Tomato Cheese Pizza", price: 150, category: "PIZZA", serialNumber: 70),
  MenuItem(id: 3014, name: "Mini Tomato Cheese Pizza", price: 130, category: "PIZZA", serialNumber: 71),
  MenuItem(id: 3015, name: "Only Cheese Pizza", price: 180, category: "PIZZA", serialNumber: 72),
  MenuItem(id: 3016, name: "Mini Only Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 73),
  MenuItem(id: 3017, name: "Mushroom Cheese Pizza", price: 220, category: "PIZZA", serialNumber: 74),
  MenuItem(id: 3018, name: "Mini Mushroom Cheese Pizza", price: 190, category: "PIZZA", serialNumber: 75),
  MenuItem(id: 3019, name: "Pineapple Cheese Pizza", price: 200, category: "PIZZA", serialNumber: 76),
  MenuItem(id: 3020, name: "Mini Pineapple Cheese Pizza", price: 170, category: "PIZZA", serialNumber: 77),
  MenuItem(id: 3021, name: "Chinese Pizza", price: 180, category: "PIZZA", serialNumber: 78),
  MenuItem(id: 3022, name: "Mini Chinese Pizza", price: 150, category: "PIZZA", serialNumber: 79),
  MenuItem(id: 3023, name: "Corn Cheese Pizza", price: 200, category: "PIZZA", serialNumber: 80),
  MenuItem(id: 3024, name: "Baby Corn Cheese Pizza", price: 220, category: "PIZZA", serialNumber: 81),

  // BURGER
  MenuItem(id: 4001, name: "Sp. Burger", price: 110, category: "BURGER", serialNumber: 82),
  MenuItem(id: 4002, name: "Veg Cheese Burger", price: 90, category: "BURGER", serialNumber: 83),
  MenuItem(id: 4003, name: "Veg Burger", price: 70, category: "BURGER", serialNumber: 84),
  MenuItem(id: 4004, name: "Paneer Burger", price: 90, category: "BURGER", serialNumber: 85),

  // HOT DOG
  MenuItem(id: 5001, name: "Sp. Hot Dog", price: 110, category: "HOT DOG", serialNumber: 86),
  MenuItem(id: 5002, name: "Veg Cheese Hot Dog", price: 90, category: "HOT DOG", serialNumber: 87),
  MenuItem(id: 5003, name: "Paneer Hot Dog", price: 90, category: "HOT DOG", serialNumber: 88),

  // PANEER SPECIAL
  MenuItem(id: 6001, name: "Paneer Lajavab", price: 220, category: "PANEER SPECIAL", serialNumber: 89),
  MenuItem(id: 6002, name: "Paneer Adrakhi", price: 220, category: "PANEER SPECIAL", serialNumber: 90),
  MenuItem(id: 6003, name: "Paneer Zafrani", price: 230, category: "PANEER SPECIAL", serialNumber: 91),
  MenuItem(id: 6004, name: "Paneer Hazari", price: 220, category: "PANEER SPECIAL", serialNumber: 92),
  MenuItem(id: 6005, name: "Paneer Balti", price: 220, category: "PANEER SPECIAL", serialNumber: 93),
  MenuItem(id: 6006, name: "Paneer Dahi", price: 230, category: "PANEER SPECIAL", serialNumber: 94),
  MenuItem(id: 6007, name: "Paneer Rajarani", price: 230, category: "PANEER SPECIAL", serialNumber: 95),
  MenuItem(id: 6008, name: "Paneer Tandoor", price: 240, category: "PANEER SPECIAL", serialNumber: 96),
  MenuItem(id: 6009, name: "Paneer Takatak", price: 230, category: "PANEER SPECIAL", serialNumber: 97),
  MenuItem(id: 6010, name: "Paneer Musiri", price: 240, category: "PANEER SPECIAL", serialNumber: 98),
  MenuItem(id: 6011, name: "Paneer Olani", price: 240, category: "PANEER SPECIAL", serialNumber: 99),
  MenuItem(id: 6012, name: "Paneer Chaklani", price: 260, category: "PANEER SPECIAL", serialNumber: 100),
  MenuItem(id: 6013, name: "Paneer Dahisodi", price: 240, category: "PANEER SPECIAL", serialNumber: 101),

  // KAJU SPECIAL
  MenuItem(id: 7001, name: "Sp. Kaju Tavaa Masala", price: 250, category: "KAJU SPECIAL", serialNumber: 102),
  MenuItem(id: 7002, name: "Sp. Kaju Kofta", price: 250, category: "KAJU SPECIAL", serialNumber: 103),
  MenuItem(id: 7003, name: "Kaju Malai", price: 250, category: "KAJU SPECIAL", serialNumber: 104),
  MenuItem(id: 7004, name: "Kaju Chatpati", price: 250, category: "KAJU SPECIAL", serialNumber: 105),
  MenuItem(id: 7005, name: "Kaju Balti", price: 250, category: "KAJU SPECIAL", serialNumber: 106),
  MenuItem(id: 7006, name: "Kaju Handi", price: 250, category: "KAJU SPECIAL", serialNumber: 107),

  // PUNJABI
  MenuItem(id: 8001, name: "Bhindi Masala", price: 120, category: "PUNJABI", serialNumber: 108),
  MenuItem(id: 8002, name: "Punjabi Thali", price: 160, category: "PUNJABI", serialNumber: 109),
  MenuItem(id: 8003, name: "Aahar Special", price: 170, category: "PUNJABI", serialNumber: 110),
  MenuItem(id: 8004, name: "Veg. Handi", price: 120, category: "PUNJABI", serialNumber: 111),
  MenuItem(id: 8005, name: "Veg. Kadai", price: 120, category: "PUNJABI", serialNumber: 112),
  MenuItem(id: 8006, name: "Veg. Angara", price: 180, category: "PUNJABI", serialNumber: 113),
  MenuItem(id: 8007, name: "Veg. Tufani", price: 140, category: "PUNJABI", serialNumber: 114),
  MenuItem(id: 8008, name: "Paneer Anguri", price: 220, category: "PUNJABI", serialNumber: 115),
  MenuItem(id: 8009, name: "Cheese Anguri", price: 220, category: "PUNJABI", serialNumber: 116),
  MenuItem(id: 8010, name: "Cheese Butter Masala", price: 210, category: "PUNJABI", serialNumber: 117),
  MenuItem(id: 8011, name: "Paneer Angara", price: 210, category: "PUNJABI", serialNumber: 118),
  MenuItem(id: 8012, name: "Paneer Chatpati", price: 180, category: "PUNJABI", serialNumber: 119),
  MenuItem(id: 8013, name: "Paneer Jodhpuri", price: 160, category: "PUNJABI", serialNumber: 120),
  MenuItem(id: 8014, name: "Panner Badsahi", price: 170, category: "PUNJABI", serialNumber: 121),
  MenuItem(id: 8015, name: "Panner Kolhapuri", price: 160, category: "PUNJABI", serialNumber: 122),
  MenuItem(id: 8016, name: "Paneer Kadai", price: 150, category: "PUNJABI", serialNumber: 123),
  MenuItem(id: 8017, name: "Paneer Tawa", price: 190, category: "PUNJABI", serialNumber: 124),
  MenuItem(id: 8018, name: "Paneer Butter Masala", price: 150, category: "PUNJABI", serialNumber: 125),
  MenuItem(id: 8019, name: "Paneer Tikka Masala", price: 150, category: "PUNJABI", serialNumber: 126),
  MenuItem(id: 8020, name: "Paneer Bhurji", price: 170, category: "PUNJABI", serialNumber: 127),
  MenuItem(id: 8021, name: "Paneer Mutter", price: 150, category: "PUNJABI", serialNumber: 128),
  MenuItem(id: 8022, name: "Paneer Toofani", price: 160, category: "PUNJABI", serialNumber: 129),
  MenuItem(id: 8023, name: "Paneer Handi", price: 140, category: "PUNJABI", serialNumber: 130),
  MenuItem(id: 8024, name: "Paneer Masala", price: 160, category: "PUNJABI", serialNumber: 131),
  MenuItem(id: 8025, name: "Paneer Palak", price: 150, category: "PUNJABI", serialNumber: 132),
  MenuItem(id: 8026, name: "Paneer Kurma", price: 160, category: "PUNJABI", serialNumber: 133),
  MenuItem(id: 8027, name: "Paneer Pasanda", price: 240, category: "PUNJABI", serialNumber: 134),
  MenuItem(id: 8028, name: "Sahi Paneer", price: 160, category: "PUNJABI", serialNumber: 135),
  MenuItem(id: 8029, name: "Paneer Express", price: 240, category: "PUNJABI", serialNumber: 136),
  MenuItem(id: 8030, name: "Aahar Special Kofta(Sweet)", price: 220, category: "PUNJABI", serialNumber: 137),
  MenuItem(id: 8031, name: "Aahar Special Malai Kofta(Spicy)", price: 190, category: "PUNJABI", serialNumber: 138),
  MenuItem(id: 8032, name: "Paneer Kofta", price: 200, category: "PUNJABI", serialNumber: 139),
  MenuItem(id: 8033, name: "Paneer Kaju", price: 180, category: "PUNJABI", serialNumber: 140),
  MenuItem(id: 8034, name: "Malai Kofta", price: 170, category: "PUNJABI", serialNumber: 141),
  MenuItem(id: 8035, name: "Veg. Kofta", price: 160, category: "PUNJABI", serialNumber: 142),
  MenuItem(id: 8036, name: "Navratna Kurma", price: 170, category: "PUNJABI", serialNumber: 143),
  MenuItem(id: 8037, name: "Veg. Kurma", price: 140, category: "PUNJABI", serialNumber: 144),
  MenuItem(id: 8038, name: "Kaju-Kari", price: 180, category: "PUNJABI", serialNumber: 145),
  MenuItem(id: 8039, name: "Kaju Masala", price: 180, category: "PUNJABI", serialNumber: 146),
  MenuItem(id: 8040, name: "Paneer Jvala", price: 210, category: "PUNJABI", serialNumber: 147),
  MenuItem(id: 8041, name: "Paneer Bullet", price: 200, category: "PUNJABI", serialNumber: 148),
  MenuItem(id: 8042, name: "Paneer Pahadi", price: 180, category: "PUNJABI", serialNumber: 149),
  MenuItem(id: 8043, name: "Paneer Matka", price: 180, category: "PUNJABI", serialNumber: 150),
  MenuItem(id: 8044, name: "Paneer Sejali", price: 180, category: "PUNJABI", serialNumber: 151),
  MenuItem(id: 8045, name: "Paneer Hungama", price: 200, category: "PUNJABI", serialNumber: 152),
  MenuItem(id: 8046, name: "Paneer Patiyala", price: 190, category: "PUNJABI", serialNumber: 153),
  MenuItem(id: 8047, name: "Paneer Mirch Masala", price: 160, category: "PUNJABI", serialNumber: 154),
  MenuItem(id: 8048, name: "Paneer Chana Masala", price: 160, category: "PUNJABI", serialNumber: 155),
  MenuItem(id: 8049, name: "Lollipop Masala", price: 160, category: "PUNJABI", serialNumber: 156),
  MenuItem(id: 8050, name: "Capsicum Masala", price: 150, category: "PUNJABI", serialNumber: 157),
  MenuItem(id: 8051, name: "Veg. Hariyali", price: 140, category: "PUNJABI", serialNumber: 158),
  MenuItem(id: 8052, name: "Veg. Hydrabadi", price: 140, category: "PUNJABI", serialNumber: 159),
  MenuItem(id: 8053, name: "Veg. Adraki", price: 120, category: "PUNJABI", serialNumber: 160),
  MenuItem(id: 8054, name: "Veg. Amrutsari", price: 160, category: "PUNJABI", serialNumber: 161),
  MenuItem(id: 8055, name: "Veg. Dilli Darbar", price: 170, category: "PUNJABI", serialNumber: 162),
  MenuItem(id: 8056, name: "Veg. Sabnam Curry", price: 170, category: "PUNJABI", serialNumber: 163),
  MenuItem(id: 8057, name: "Veg. Divani Handi", price: 160, category: "PUNJABI", serialNumber: 164),
  MenuItem(id: 8058, name: "Veg. Sabnam Kofta", price: 160, category: "PUNJABI", serialNumber: 165),
  MenuItem(id: 8059, name: "Lajvab Kofta", price: 200, category: "PUNJABI", serialNumber: 166),
  MenuItem(id: 8060, name: "Kaju Khoya", price: 180, category: "PUNJABI", serialNumber: 167),
  MenuItem(id: 8061, name: "Veg. Tiranga", price: 220, category: "PUNJABI", serialNumber: 168),
  MenuItem(id: 8062, name: "Mashroom Masala", price: 180, category: "PUNJABI", serialNumber: 169),
  MenuItem(id: 8063, name: "Stuff Tometo", price: 140, category: "PUNJABI", serialNumber: 170),
  MenuItem(id: 8064, name: "Dum Aloo", price: 140, category: "PUNJABI", serialNumber: 171),
  MenuItem(id: 8065, name: "Dum Aloo Kashmiri", price: 150, category: "PUNJABI", serialNumber: 172),
  MenuItem(id: 8066, name: "Jeera Aloo", price: 110, category: "PUNJABI", serialNumber: 173),
  MenuItem(id: 8067, name: "Tometo Batata", price: 120, category: "PUNJABI", serialNumber: 174),
  MenuItem(id: 8068, name: "Papad Roll Masala", price: 160, category: "PUNJABI", serialNumber: 175),
  MenuItem(id: 8069, name: "Bengan Masala", price: 120, category: "PUNJABI", serialNumber: 176),
  MenuItem(id: 8070, name: "Bengan Bhatta", price: 130, category: "PUNJABI", serialNumber: 177),
  MenuItem(id: 8071, name: "Dal Fry", price: 100, category: "PUNJABI", serialNumber: 178),
  MenuItem(id: 8072, name: "Butter Dal Fry", price: 130, category: "PUNJABI", serialNumber: 179),
  MenuItem(id: 8073, name: "Dal Tadka", price: 130, category: "PUNJABI", serialNumber: 180),
  MenuItem(id: 8074, name: "Palak Mutter", price: 120, category: "PUNJABI", serialNumber: 181),
  MenuItem(id: 8075, name: "Aloo Palak", price: 120, category: "PUNJABI", serialNumber: 182),
  MenuItem(id: 8076, name: "Chana Masala", price: 130, category: "PUNJABI", serialNumber: 183),
  MenuItem(id: 8077, name: "Alu Gobi", price: 120, category: "PUNJABI", serialNumber: 184),
  MenuItem(id: 8078, name: "Alu Mutter", price: 120, category: "PUNJABI", serialNumber: 185),
  MenuItem(id: 8079, name: "Mix Veg.", price: 120, category: "PUNJABI", serialNumber: 186),
  MenuItem(id: 8080, name: "Veg. Kolhapuri", price: 140, category: "PUNJABI", serialNumber: 187),
  MenuItem(id: 8081, name: "Veg. Makhanwala", price: 150, category: "PUNJABI", serialNumber: 188),
  MenuItem(id: 8082, name: "Veg. Jaypuri", price: 140, category: "PUNJABI", serialNumber: 189),
  MenuItem(id: 8083, name: "Palak Masala", price: 120, category: "PUNJABI", serialNumber: 190),
  MenuItem(id: 8084, name: "Bhindi Fry", price: 120, category: "PUNJABI", serialNumber: 191),

  // TANDOORI
  MenuItem(id: 9001, name: "Tandoori Roti", price: 20, category: "TANDOORI", serialNumber: 192),
  MenuItem(id: 9002, name: "Amul Butter Roti", price: 30, category: "TANDOORI", serialNumber: 193),
  MenuItem(id: 9018, name: "Tava Amul Butter Roti", price: 25, category: "TANDOORI", serialNumber: 193),
  MenuItem(id: 9003, name: "Butter Parotha", price: 50, category: "TANDOORI", serialNumber: 194),
  MenuItem(id: 9004, name: "Sada Parotha", price: 40, category: "TANDOORI", serialNumber: 195),
  MenuItem(id: 9005, name: "Butter Nan", price: 50, category: "TANDOORI", serialNumber: 196),
  MenuItem(id: 9006, name: "Sada Nan", price: 40, category: "TANDOORI", serialNumber: 197),
  MenuItem(id: 9007, name: "Kashmiri Nan", price: 70, category: "TANDOORI", serialNumber: 198),
  MenuItem(id: 9008, name: "Masala Parotha", price: 70, category: "TANDOORI", serialNumber: 199),
  MenuItem(id: 9009, name: "Stuff Parotha", price: 70, category: "TANDOORI", serialNumber: 200),
  MenuItem(id: 9010, name: "Masala Kulcha", price: 70, category: "TANDOORI", serialNumber: 201),
  MenuItem(id: 9011, name: "Sada Kulcha", price: 50, category: "TANDOORI", serialNumber: 202),
  MenuItem(id: 9012, name: "Tava Roti", price: 15, category: "TANDOORI", serialNumber: 203),
  MenuItem(id: 9013, name: "Tava Roti Butter", price: 20, category: "TANDOORI", serialNumber: 204),
  MenuItem(id: 9014, name: "Paneer Parotha", price: 80, category: "TANDOORI", serialNumber: 205),
  MenuItem(id: 9015, name: "Paneer Nan", price: 80, category: "TANDOORI", serialNumber: 206),
  MenuItem(id: 9016, name: "Onion Nan", price: 60, category: "TANDOORI", serialNumber: 207),
  MenuItem(id: 9017, name: "Cheese Nan", price: 90, category: "TANDOORI", serialNumber: 208),
  MenuItem(id: 9019, name: "Garlic Nan", price: 70, category: "TANDOORI", serialNumber: 208),
  MenuItem(id: 9020, name: "Garlic Chesses", price: 100, category: "TANDOORI", serialNumber: 208),

  // PAPAD & SALAD
  MenuItem(id: 10001, name: "Rosted Papad", price: 20, category: "PAPAD & SALAD", serialNumber: 209),
  MenuItem(id: 10002, name: "Fry Papad", price: 30, category: "PAPAD & SALAD", serialNumber: 210),
  MenuItem(id: 10003, name: "Masala Papad", price: 40, category: "PAPAD & SALAD", serialNumber: 211),
  MenuItem(id: 10004, name: "Butter Milk", price: 25, category: "PAPAD & SALAD", serialNumber: 212),
  MenuItem(id: 10005, name: "Green Salad", price: 80, category: "PAPAD & SALAD", serialNumber: 213),
  MenuItem(id: 10006, name: "Finger Chips", price: 100, category: "PAPAD & SALAD", serialNumber: 214),

  // SOUP
  MenuItem(id: 11001, name: "Tomato Soup", price: 80, category: "SOUP", serialNumber: 215),
  MenuItem(id: 11002, name: "Cream of Tomato Soup", price: 90, category: "SOUP", serialNumber: 216),
  MenuItem(id: 11003, name: "Hot & Sour Soup", price: 80, category: "SOUP", serialNumber: 217),
  MenuItem(id: 11004, name: "Veg. Manchow Soup", price: 80, category: "SOUP", serialNumber: 218),
  MenuItem(id: 11005, name: "Cream of Veg. Soup", price: 80, category: "SOUP", serialNumber: 219),
  MenuItem(id: 11006, name: "Sweet Corn Veg. Soup", price: 80, category: "SOUP", serialNumber: 220),
  MenuItem(id: 11007, name: "Sweet Corn Plain Soup", price: 80, category: "SOUP", serialNumber: 221),
  MenuItem(id: 11008, name: "Mushroom Soup", price: 90, category: "SOUP", serialNumber: 222),
  MenuItem(id: 11009, name: "Ministrone Soup", price: 80, category: "SOUP", serialNumber: 223),
  MenuItem(id: 11010, name: "Veg. Clear Soup", price: 70, category: "SOUP", serialNumber: 224),
  MenuItem(id: 11011, name: "Green Peas Soup", price: 70, category: "SOUP", serialNumber: 225),
  MenuItem(id: 11012, name: "Veg Noodles Soup", price: 80, category: "SOUP", serialNumber: 226),
  MenuItem(id: 11013, name: "Royal Veg. Soup", price: 90, category: "SOUP", serialNumber: 227),
  MenuItem(id: 11014, name: "Cocktail Soup", price: 90, category: "SOUP", serialNumber: 228),

  // NOODLES
  MenuItem(id: 12001, name: "Bombay Bhel", price: 150, category: "NOODLES", serialNumber: 229),
  MenuItem(id: 12002, name: "Aaisi paisi Noodles", price: 170, category: "NOODLES", serialNumber: 230),
  MenuItem(id: 12003, name: "Hakka Noodles", price: 150, category: "NOODLES", serialNumber: 231),
  MenuItem(id: 12004, name: "Singapuri Noodles", price: 160, category: "NOODLES", serialNumber: 232),
  MenuItem(id: 12005, name: "Veg. Rice & Noodles", price: 150, category: "NOODLES", serialNumber: 233),
  MenuItem(id: 12006, name: "Schwan Noodles", price: 150, category: "NOODLES", serialNumber: 234),
  MenuItem(id: 12007, name: "Fried Noodles", price: 170, category: "NOODLES", serialNumber: 235),
  MenuItem(id: 12008, name: "Combination Noodles", price: 150, category: "NOODLES", serialNumber: 236),
  MenuItem(id: 12009, name: "Mashroom Noodles", price: 160, category: "NOODLES", serialNumber: 237),
  MenuItem(id: 12010, name: "Tripple's Schzwan Noodles", price: 200, category: "NOODLES", serialNumber: 238),
  MenuItem(id: 12011, name: "American Chopsy", price: 160, category: "NOODLES", serialNumber: 239),
  MenuItem(id: 12012, name: "Mashroom Chopsy", price: 170, category: "NOODLES", serialNumber: 240),
  MenuItem(id: 12013, name: "Chinese Bhel", price: 150, category: "NOODLES", serialNumber: 241),
  MenuItem(id: 12014, name: "Garlic Chawmin (liquid)", price: 160, category: "NOODLES", serialNumber: 242),
  MenuItem(id: 12015, name: "Veg. Chawmin (liquid)", price: 150, category: "NOODLES", serialNumber: 243),
  MenuItem(id: 12016, name: "Huanan Noodles", price: 200, category: "NOODLES", serialNumber: 244),

  // VEG. FOOD & GRAVY
  MenuItem(id: 13001, name: "Paneer bullet", price: 220, category: "VEG. FOOD & GRAVY", serialNumber: 245),
  MenuItem(id: 13002, name: "Paneer Schzwen Roll", price: 240, category: "VEG. FOOD & GRAVY", serialNumber: 246),
  MenuItem(id: 13003, name: "Veg. Green Ball", price: 160, category: "VEG. FOOD & GRAVY", serialNumber: 247),
  MenuItem(id: 13004, name: "Veg. Krivsi", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 248),
  MenuItem(id: 13005, name: "Mashroom Roll", price: 220, category: "VEG. FOOD & GRAVY", serialNumber: 249),
  MenuItem(id: 13006, name: "Veg. Manchurian (Liquid)", price: 160, category: "VEG. FOOD & GRAVY", serialNumber: 250),
  MenuItem(id: 13007, name: "Veg. Manchurian (Dry)", price: 160, category: "VEG. FOOD & GRAVY", serialNumber: 251),
  MenuItem(id: 13008, name: "Mashroom Manchurian (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 252),
  MenuItem(id: 13009, name: "Baby Corn Manchurian (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 253),
  MenuItem(id: 13010, name: "Baby Corn Manchurian (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 254),
  MenuItem(id: 13011, name: "Baby Corn Chilli (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 255),
  MenuItem(id: 13012, name: "Paneer Manchurian (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 256),
  MenuItem(id: 13013, name: "Paneer Manchurian (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 257),
  MenuItem(id: 13014, name: "Paneer Chilli (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 258),
  MenuItem(id: 13015, name: "Paneer Chilli (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 259),
  MenuItem(id: 13016, name: "Paneer mamtal (Dry)", price: 250, category: "VEG. FOOD & GRAVY", serialNumber: 260),
  MenuItem(id: 13017, name: "Paneer '65 (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 261),
  MenuItem(id: 13018, name: "Paneer '65(Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 262),
  MenuItem(id: 13019, name: "Cocktail (Dry/Liquid)", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 263),
  MenuItem(id: 13020, name: "Veg. Chilli (Dry)", price: 170, category: "VEG. FOOD & GRAVY", serialNumber: 264),
  MenuItem(id: 13021, name: "Veg. Chilli (Liquid)", price: 170, category: "VEG. FOOD & GRAVY", serialNumber: 265),
  MenuItem(id: 13022, name: "Veg. '65 (Dry)", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 266),
  MenuItem(id: 13023, name: "Veg ' 65(Liquid)", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 267),
  MenuItem(id: 13024, name: "Potato Chilli", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 268),
  MenuItem(id: 13025, name: "Veg. Lollipop", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 269),

  // RICE DISH
  MenuItem(id: 14001, name: "Huanan Rice", price: 200, category: "RICE DISH", serialNumber: 270),
  MenuItem(id: 14002, name: "Hongkong Rice", price: 200, category: "RICE DISH", serialNumber: 271),
  MenuItem(id: 14003, name: "Aahar Sp. Rice", price: 220, category: "RICE DISH", serialNumber: 272),
  MenuItem(id: 14004, name: "Veg. Fried Rice", price: 150, category: "RICE DISH", serialNumber: 273),
  MenuItem(id: 14005, name: "Mix Veg. Fried Rice", price: 150, category: "RICE DISH", serialNumber: 274),
  MenuItem(id: 14006, name: "Veg. Ginger Fried Rice", price: 150, category: "RICE DISH", serialNumber: 275),
  MenuItem(id: 14007, name: "Garlic Fried Rice", price: 170, category: "RICE DISH", serialNumber: 276),
  MenuItem(id: 14008, name: "Combination Rice", price: 160, category: "RICE DISH", serialNumber: 277),
  MenuItem(id: 14009, name: "Mashroom Fried Rice", price: 190, category: "RICE DISH", serialNumber: 278),
  MenuItem(id: 14010, name: "Schezwan Fried Rice", price: 160, category: "RICE DISH", serialNumber: 279),
  MenuItem(id: 14011, name: "Tripple Schezwan Rice", price: 200, category: "RICE DISH", serialNumber: 280),
  MenuItem(id: 14012, name: "Singapoori Fried Rice", price: 160, category: "RICE DISH", serialNumber: 281),
  MenuItem(id: 14013, name: "Chinese Veg. Pulao", price: 150, category: "RICE DISH", serialNumber: 282),
  MenuItem(id: 14014, name: "Paneer Pulao", price: 200, category: "RICE DISH", serialNumber: 283),
  MenuItem(id: 14015, name: "Cheese Pulao", price: 220, category: "RICE DISH", serialNumber: 284),
  MenuItem(id: 14016, name: "Punjabi Veg. Pulao", price: 160, category: "RICE DISH", serialNumber: 285),
  MenuItem(id: 14017, name: "Veg. Kashmiri Pulao", price: 180, category: "RICE DISH", serialNumber: 286),
  MenuItem(id: 14018, name: "Green Peas Pulao", price: 150, category: "RICE DISH", serialNumber: 287),
  MenuItem(id: 14019, name: "Veg. Biryani", price: 160, category: "RICE DISH", serialNumber: 288),
  MenuItem(id: 14020, name: "Hydrabadi Biryani", price: 160, category: "RICE DISH", serialNumber: 289),
  MenuItem(id: 14021, name: "Jira Rice", price: 110, category: "RICE DISH", serialNumber: 290),
  MenuItem(id: 14022, name: "Plain Rice", price: 90, category: "RICE DISH", serialNumber: 291),
  MenuItem(id: 14023, name: "Masala Rice", price: 160, category: "RICE DISH", serialNumber: 292),
  MenuItem(id: 14024, name: "Half Jira Rice", price: 80, category: "RICE DISH", serialNumber: 293),
  MenuItem(id: 14025, name: "Half Plain Rice", price: 70, category: "RICE DISH", serialNumber: 294),
  MenuItem(id: 14026, name: "Half Masala Rice", price: 110, category: "RICE DISH", serialNumber: 295),
  MenuItem(id: 14027, name: "Veg.Rayta", price: 80, category: "RICE DISH", serialNumber: 296),
  MenuItem(id: 14028, name: "Kashmiri Rayta", price: 120, category: "RICE DISH", serialNumber: 297),
  MenuItem(id: 14029, name: "Pineapple Rayta", price: 100, category: "RICE DISH", serialNumber: 298),
  MenuItem(id: 14030, name: "Bundi Rayta", price: 90, category: "RICE DISH", serialNumber: 299),

  // SIZZLERS
  MenuItem(id: 15001, name: "Veg. Sizzlers", price: 250, category: "SIZZLERS", serialNumber: 300),
  MenuItem(id: 15002, name: "Mix Veg. Sizzlers", price: 250, category: "SIZZLERS", serialNumber: 301),
  MenuItem(id: 15003, name: "Combination Sizzlers", price: 250, category: "SIZZLERS", serialNumber: 302),
  MenuItem(id: 15004, name: "Mix Grill Sizzlers", price: 250, category: "SIZZLERS", serialNumber: 303),
  MenuItem(id: 15005, name: "Chinese Sizzlers", price: 250, category: "SIZZLERS", serialNumber: 304),
  MenuItem(id: 15006, name: "Garlic Ball (dry/liquid)", price: 160, category: "SIZZLERS", serialNumber: 305),
  MenuItem(id: 15007, name: "Ginjer Ball (dry/liquid)", price: 160, category: "SIZZLERS", serialNumber: 306),
  MenuItem(id: 15008, name: "Veg. Cheese Ball (dry)", price: 180, category: "SIZZLERS", serialNumber: 307),
  MenuItem(id: 15009, name: "Veg. Spring roll", price: 200, category: "SIZZLERS", serialNumber: 308),
  MenuItem(id: 15010, name: "Hara Bhara Kabab", price: 200, category: "SIZZLERS", serialNumber: 309),
  MenuItem(id: 15011, name: "Schzwan Ball (dry/liquid)", price: 170, category: "SIZZLERS", serialNumber: 310),

  // COLD DRINKS
  MenuItem(id: 16001, name: "Soft Drink(300 ml.)", price: 40, category: "COLD DRINKS", serialNumber: 311),
  MenuItem(id: 16002, name: "Soft Drink(1.5 Lit.)", price: 90, category: "COLD DRINKS", serialNumber: 312),
  MenuItem(id: 16003, name: "Soft Drink(2 Lit.)", price: 110, category: "COLD DRINKS", serialNumber: 313),
  MenuItem(id: 16004, name: "Soda", price: 20, category: "COLD DRINKS", serialNumber: 314),
  MenuItem(id: 16005, name: "Min. Water", price: 20, category: "COLD DRINKS", serialNumber: 315),
];
