import 'app_state.dart';

final List<CategoryModel> newDefaultCategories = [
  CategoryModel(name: "SANDWICH", serialNumber: 1),
  CategoryModel(name: "GRILLED SANDWICH", serialNumber: 2),
  CategoryModel(name: "PIZZA", serialNumber: 3),
  CategoryModel(name: "BURGER & HOT DOG", serialNumber: 4),
  CategoryModel(name: "PANEER SPECIAL", serialNumber: 5),
  CategoryModel(name: "KAJU SPECIAL", serialNumber: 6),
  CategoryModel(name: "PUNJABI", serialNumber: 7),
  CategoryModel(name: "TANDOORI", serialNumber: 8),
  CategoryModel(name: "PAPAD, SALAD & SOUP", serialNumber: 9),
  CategoryModel(name: "NOODLES", serialNumber: 10),
  CategoryModel(name: "VEG. FOOD & GRAVY", serialNumber: 11),
  CategoryModel(name: "RICE DISH", serialNumber: 12),
  CategoryModel(name: "SIZZLERS & COLD DRINKS", serialNumber: 13),
];

final List<MenuItem> newDefaultMenu = [
  // SANDWICH
  MenuItem(id: 1, name: "Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 1),
  MenuItem(id: 2, name: "Veg. Sandwich", price: 60, category: "SANDWICH", serialNumber: 2),
  MenuItem(id: 3, name: "Jain Veg. Sandwich", price: 60, category: "SANDWICH", serialNumber: 3),
  MenuItem(id: 4, name: "Bread Butter", price: 60, category: "SANDWICH", serialNumber: 4),
  MenuItem(id: 5, name: "Chatni Bread Butter", price: 60, category: "SANDWICH", serialNumber: 5),
  MenuItem(id: 6, name: "Jam Bread Butter", price: 60, category: "SANDWICH", serialNumber: 6),
  MenuItem(id: 7, name: "Jain Veg. Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 7),
  MenuItem(id: 8, name: "Bread Butter Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 8),
  MenuItem(id: 9, name: "Chatni Toast Sandwich", price: 60, category: "SANDWICH", serialNumber: 9),
  MenuItem(id: 10, name: "Jam Toast Sandwich", price: 70, category: "SANDWICH", serialNumber: 10),
  MenuItem(id: 11, name: "Pizza Masala Toast Sandwich", price: 70, category: "SANDWICH", serialNumber: 11),
  MenuItem(id: 12, name: "Jam Veg. Sandwich", price: 60, category: "SANDWICH", serialNumber: 12),
  MenuItem(id: 13, name: "Aahar Sp. Sandwich", price: 90, category: "SANDWICH", serialNumber: 13),
  MenuItem(id: 14, name: "Veg. Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 14),
  MenuItem(id: 15, name: "Bread Butter Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 15),
  MenuItem(id: 16, name: "Jam Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 16),
  MenuItem(id: 17, name: "Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 17),
  MenuItem(id: 18, name: "Veg. Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 18),
  MenuItem(id: 19, name: "Masala Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 19),
  MenuItem(id: 20, name: "Jam Cheese Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 20),
  MenuItem(id: 21, name: "Capsicum Cheese Sandwich", price: 90, category: "SANDWICH", serialNumber: 21),
  MenuItem(id: 22, name: "Sp. Cheese Pizza Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 22),
  MenuItem(id: 23, name: "Icey Picey Cheese Toast Sandwich", price: 120, category: "SANDWICH", serialNumber: 23),
  MenuItem(id: 24, name: "Cocktail Cheese Toast Sandwich", price: 110, category: "SANDWICH", serialNumber: 24),
  MenuItem(id: 25, name: "Pineapple Cheese Toast Sandwich", price: 100, category: "SANDWICH", serialNumber: 25),
  MenuItem(id: 26, name: "Garlic Cheese Toast", price: 90, category: "SANDWICH", serialNumber: 26),
  MenuItem(id: 27, name: "Tometo Cheese Toast", price: 90, category: "SANDWICH", serialNumber: 27),
  MenuItem(id: 28, name: "Club Sandwich", price: 120, category: "SANDWICH", serialNumber: 28),
  MenuItem(id: 29, name: "Paneer Pakoda Toast Sandwich", price: 100, category: "SANDWICH", serialNumber: 29),
  MenuItem(id: 30, name: "Icey Picey Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 30),
  MenuItem(id: 31, name: "Cocktail Toast Sandwich", price: 90, category: "SANDWICH", serialNumber: 31),
  MenuItem(id: 32, name: "Pineapple Toast Sandwich", price: 80, category: "SANDWICH", serialNumber: 32),

  // GRILLED SANDWICH
  MenuItem(id: 33, name: "Only Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 33),
  MenuItem(id: 34, name: "Mini Only Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 34),
  MenuItem(id: 35, name: "Sp. Veg. Cheese Grilled Sandwich", price: 190, category: "GRILLED SANDWICH", serialNumber: 35),
  MenuItem(id: 36, name: "Mini Sp. Veg. Cheese Grilled Sandwich", price: 160, category: "GRILLED SANDWICH", serialNumber: 36),
  MenuItem(id: 37, name: "Pineapple Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 37),
  MenuItem(id: 38, name: "Mini Pineapple Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 38),
  MenuItem(id: 39, name: "Schezwan Cheese Grilled Sandwich", price: 210, category: "GRILLED SANDWICH", serialNumber: 39),
  MenuItem(id: 40, name: "Mini Schezwan Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 40),
  MenuItem(id: 41, name: "Mushroom Cheese Grilled Sandwich", price: 220, category: "GRILLED SANDWICH", serialNumber: 41),
  MenuItem(id: 42, name: "Mini Mushroom Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 42),
  MenuItem(id: 43, name: "Capsicum Onion Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 43),
  MenuItem(id: 44, name: "Mini Capsicum Onion Cheese Grilled Sandwich", price: 150, category: "GRILLED SANDWICH", serialNumber: 44),
  MenuItem(id: 45, name: "Masala Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 45),
  MenuItem(id: 46, name: "Mini Masala Cheese Grilled Sandwich", price: 170, category: "GRILLED SANDWICH", serialNumber: 46),
  MenuItem(id: 47, name: "Veg. Grilled Sandwich", price: 160, category: "GRILLED SANDWICH", serialNumber: 47),
  MenuItem(id: 48, name: "Mini Veg. Grilled Sandwich", price: 130, category: "GRILLED SANDWICH", serialNumber: 48),
  MenuItem(id: 49, name: "Italian Cheese Grilled Sandwich", price: 210, category: "GRILLED SANDWICH", serialNumber: 49),
  MenuItem(id: 50, name: "Mini Italian Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 50),
  MenuItem(id: 51, name: "Jam Veg. Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 51),
  MenuItem(id: 52, name: "Mini Jam Veg. Cheese Grilled Sandwich", price: 180, category: "GRILLED SANDWICH", serialNumber: 52),
  MenuItem(id: 53, name: "Veg. Corn Cheese Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 53),
  MenuItem(id: 54, name: "Veg. Paneer Grilled Sandwich", price: 200, category: "GRILLED SANDWICH", serialNumber: 54),
  MenuItem(id: 55, name: "Sp. Veg. Paneer Cheese Grilled Sandwich", price: 220, category: "GRILLED SANDWICH", serialNumber: 55),
  MenuItem(id: 56, name: "Lumsum Cheese Grilled Sandwich", price: 220, category: "GRILLED SANDWICH", serialNumber: 56),
  MenuItem(id: 57, name: "Chinese Grilled Sandwich", price: 210, category: "GRILLED SANDWICH", serialNumber: 57),

  // PIZZA
  MenuItem(id: 58, name: "Aahar Sp. Veg. Cheese Pizza", price: 180, category: "PIZZA", serialNumber: 58),
  MenuItem(id: 59, name: "Mini Aahar Sp. Veg. Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 59),
  MenuItem(id: 60, name: "Veg. Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 60),
  MenuItem(id: 61, name: "Mini Veg. Cheese Pizza", price: 140, category: "PIZZA", serialNumber: 61),
  MenuItem(id: 62, name: "Sp. Jain Veg. Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 62),
  MenuItem(id: 63, name: "Mini Sp. Jain Veg. Cheese Pizza", price: 130, category: "PIZZA", serialNumber: 63),
  MenuItem(id: 64, name: "Italian Pizza", price: 170, category: "PIZZA", serialNumber: 64),
  MenuItem(id: 65, name: "Mini Italian Pizza", price: 150, category: "PIZZA", serialNumber: 65),
  MenuItem(id: 66, name: "Jam Cheese Pizza", price: 180, category: "PIZZA", serialNumber: 66),
  MenuItem(id: 67, name: "Mini Jam Cheese Pizza", price: 150, category: "PIZZA", serialNumber: 67),
  MenuItem(id: 68, name: "Capsicum Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 68),
  MenuItem(id: 69, name: "Mini Capsicum Cheese Pizza", price: 140, category: "PIZZA", serialNumber: 69),
  MenuItem(id: 70, name: "Tomato Cheese Pizza", price: 150, category: "PIZZA", serialNumber: 70),
  MenuItem(id: 71, name: "Mini Tomato Cheese Pizza", price: 130, category: "PIZZA", serialNumber: 71),
  MenuItem(id: 72, name: "Only Cheese Pizza", price: 180, category: "PIZZA", serialNumber: 72),
  MenuItem(id: 73, name: "Mini Only Cheese Pizza", price: 160, category: "PIZZA", serialNumber: 73),
  MenuItem(id: 74, name: "Mushroom Cheese Pizza", price: 220, category: "PIZZA", serialNumber: 74),
  MenuItem(id: 75, name: "Mini Mushroom Cheese Pizza", price: 190, category: "PIZZA", serialNumber: 75),
  MenuItem(id: 76, name: "Pineapple Cheese Pizza", price: 200, category: "PIZZA", serialNumber: 76),
  MenuItem(id: 77, name: "Mini Pineapple Cheese Pizza", price: 170, category: "PIZZA", serialNumber: 77),
  MenuItem(id: 78, name: "Chinese Pizza", price: 180, category: "PIZZA", serialNumber: 78),
  MenuItem(id: 79, name: "Mini Chinese Pizza", price: 150, category: "PIZZA", serialNumber: 79),
  MenuItem(id: 80, name: "Corn Cheese Pizza", price: 200, category: "PIZZA", serialNumber: 80),
  MenuItem(id: 81, name: "Baby Corn Cheese Pizza", price: 220, category: "PIZZA", serialNumber: 81),

  // BURGER & HOT DOG
  MenuItem(id: 82, name: "Sp. Burger", price: 110, category: "BURGER & HOT DOG", serialNumber: 82),
  MenuItem(id: 83, name: "Veg Cheese Burger", price: 90, category: "BURGER & HOT DOG", serialNumber: 83),
  MenuItem(id: 84, name: "Veg Burger", price: 70, category: "BURGER & HOT DOG", serialNumber: 84),
  MenuItem(id: 85, name: "Paneer Burger", price: 90, category: "BURGER & HOT DOG", serialNumber: 85),
  MenuItem(id: 86, name: "Sp. Hot Dog", price: 110, category: "BURGER & HOT DOG", serialNumber: 86),
  MenuItem(id: 87, name: "Veg Cheese Hot Dog", price: 90, category: "BURGER & HOT DOG", serialNumber: 87),
  MenuItem(id: 88, name: "Paneer Hot Dog", price: 90, category: "BURGER & HOT DOG", serialNumber: 88),

  // PANEER SPECIAL
  MenuItem(id: 89, name: "Paneer Lajavab", price: 220, category: "PANEER SPECIAL", serialNumber: 89),
  MenuItem(id: 90, name: "Paneer Adrakhi", price: 220, category: "PANEER SPECIAL", serialNumber: 90),
  MenuItem(id: 91, name: "Paneer Zafrani", price: 230, category: "PANEER SPECIAL", serialNumber: 91),
  MenuItem(id: 92, name: "Paneer Hazari", price: 220, category: "PANEER SPECIAL", serialNumber: 92),
  MenuItem(id: 93, name: "Paneer Balti", price: 220, category: "PANEER SPECIAL", serialNumber: 93),
  MenuItem(id: 94, name: "Paneer Dahi", price: 230, category: "PANEER SPECIAL", serialNumber: 94),
  MenuItem(id: 95, name: "Paneer Rajarani", price: 230, category: "PANEER SPECIAL", serialNumber: 95),
  MenuItem(id: 96, name: "Paneer Tandoor", price: 240, category: "PANEER SPECIAL", serialNumber: 96),
  MenuItem(id: 97, name: "Paneer Takatak", price: 230, category: "PANEER SPECIAL", serialNumber: 97),
  MenuItem(id: 98, name: "Paneer Musiri", price: 240, category: "PANEER SPECIAL", serialNumber: 98),
  MenuItem(id: 99, name: "Paneer Olani", price: 240, category: "PANEER SPECIAL", serialNumber: 99),
  MenuItem(id: 100, name: "Paneer Chaklani", price: 260, category: "PANEER SPECIAL", serialNumber: 100),
  MenuItem(id: 101, name: "Paneer Dahisodi", price: 240, category: "PANEER SPECIAL", serialNumber: 101),

  // KAJU SPECIAL
  MenuItem(id: 102, name: "Sp. Kaju Tavaa Masala", price: 250, category: "KAJU SPECIAL", serialNumber: 102),
  MenuItem(id: 103, name: "Sp. Kaju Kofta", price: 250, category: "KAJU SPECIAL", serialNumber: 103),
  MenuItem(id: 104, name: "Kaju Malai", price: 250, category: "KAJU SPECIAL", serialNumber: 104),
  MenuItem(id: 105, name: "Kaju Chatpati", price: 250, category: "KAJU SPECIAL", serialNumber: 105),
  MenuItem(id: 106, name: "Kaju Balti", price: 250, category: "KAJU SPECIAL", serialNumber: 106),
  MenuItem(id: 107, name: "Kaju Handi", price: 250, category: "KAJU SPECIAL", serialNumber: 107),

  // PUNJABI
  MenuItem(id: 108, name: "Bhindi Masala", price: 120, category: "PUNJABI", serialNumber: 108),
  MenuItem(id: 109, name: "Punjabi Thali", price: 160, category: "PUNJABI", serialNumber: 109),
  MenuItem(id: 110, name: "Aahar Special", price: 170, category: "PUNJABI", serialNumber: 110),
  MenuItem(id: 111, name: "Veg. Handi", price: 120, category: "PUNJABI", serialNumber: 111),
  MenuItem(id: 112, name: "Veg. Kadai", price: 120, category: "PUNJABI", serialNumber: 112),
  MenuItem(id: 113, name: "Veg. Angara", price: 180, category: "PUNJABI", serialNumber: 113),
  MenuItem(id: 114, name: "Veg. Tufani", price: 140, category: "PUNJABI", serialNumber: 114),
  MenuItem(id: 115, name: "Paneer Anguri", price: 220, category: "PUNJABI", serialNumber: 115),
  MenuItem(id: 116, name: "Cheese Anguri", price: 220, category: "PUNJABI", serialNumber: 116),
  MenuItem(id: 117, name: "Cheese Butter Masala", price: 210, category: "PUNJABI", serialNumber: 117),
  MenuItem(id: 118, name: "Paneer Angara", price: 210, category: "PUNJABI", serialNumber: 118),
  MenuItem(id: 119, name: "Paneer Chatpati", price: 180, category: "PUNJABI", serialNumber: 119),
  MenuItem(id: 120, name: "Paneer Jodhpuri", price: 160, category: "PUNJABI", serialNumber: 120),
  MenuItem(id: 121, name: "Panner Badsahi", price: 170, category: "PUNJABI", serialNumber: 121),
  MenuItem(id: 122, name: "Panner Kolhapuri", price: 160, category: "PUNJABI", serialNumber: 122),
  MenuItem(id: 123, name: "Paneer Kadai", price: 150, category: "PUNJABI", serialNumber: 123),
  MenuItem(id: 124, name: "Paneer Tawa", price: 190, category: "PUNJABI", serialNumber: 124),
  MenuItem(id: 125, name: "Paneer Butter Masala", price: 150, category: "PUNJABI", serialNumber: 125),
  MenuItem(id: 126, name: "Paneer Tikka Masala", price: 150, category: "PUNJABI", serialNumber: 126),
  MenuItem(id: 127, name: "Paneer Bhurji", price: 170, category: "PUNJABI", serialNumber: 127),
  MenuItem(id: 128, name: "Paneer Mutter", price: 150, category: "PUNJABI", serialNumber: 128),
  MenuItem(id: 129, name: "Paneer Toofani", price: 160, category: "PUNJABI", serialNumber: 129),
  MenuItem(id: 130, name: "Paneer Handi", price: 140, category: "PUNJABI", serialNumber: 130),
  MenuItem(id: 131, name: "Paneer Masala", price: 160, category: "PUNJABI", serialNumber: 131),
  MenuItem(id: 132, name: "Paneer Palak", price: 150, category: "PUNJABI", serialNumber: 132),
  MenuItem(id: 133, name: "Paneer Kurma", price: 160, category: "PUNJABI", serialNumber: 133),
  MenuItem(id: 134, name: "Paneer Pasanda", price: 240, category: "PUNJABI", serialNumber: 134),
  MenuItem(id: 135, name: "Sahi Paneer", price: 160, category: "PUNJABI", serialNumber: 135),
  MenuItem(id: 136, name: "Paneer Express", price: 240, category: "PUNJABI", serialNumber: 136),
  MenuItem(id: 137, name: "Aahar Special Kofta(Sweet)", price: 220, category: "PUNJABI", serialNumber: 137),
  MenuItem(id: 138, name: "Aahar Special Malai Kofta(Spicy)", price: 190, category: "PUNJABI", serialNumber: 138),
  MenuItem(id: 139, name: "Paneer Kofta", price: 200, category: "PUNJABI", serialNumber: 139),
  MenuItem(id: 140, name: "Paneer Kaju", price: 180, category: "PUNJABI", serialNumber: 140),
  MenuItem(id: 141, name: "Malai Kofta", price: 170, category: "PUNJABI", serialNumber: 141),
  MenuItem(id: 142, name: "Veg. Kofta", price: 160, category: "PUNJABI", serialNumber: 142),
  MenuItem(id: 143, name: "Navratna Kurma", price: 170, category: "PUNJABI", serialNumber: 143),
  MenuItem(id: 144, name: "Veg. Kurma", price: 140, category: "PUNJABI", serialNumber: 144),
  MenuItem(id: 145, name: "Kaju-Kari", price: 180, category: "PUNJABI", serialNumber: 145),
  MenuItem(id: 146, name: "Kaju Masala", price: 180, category: "PUNJABI", serialNumber: 146),
  MenuItem(id: 147, name: "Paneer Jvala", price: 210, category: "PUNJABI", serialNumber: 147),
  MenuItem(id: 148, name: "Paneer Bullet", price: 200, category: "PUNJABI", serialNumber: 148),
  MenuItem(id: 149, name: "Paneer Pahadi", price: 180, category: "PUNJABI", serialNumber: 149),
  MenuItem(id: 150, name: "Paneer Matka", price: 180, category: "PUNJABI", serialNumber: 150),
  MenuItem(id: 151, name: "Paneer Sejali", price: 180, category: "PUNJABI", serialNumber: 151),
  MenuItem(id: 152, name: "Paneer Hungama", price: 200, category: "PUNJABI", serialNumber: 152),
  MenuItem(id: 153, name: "Paneer Patiyala", price: 190, category: "PUNJABI", serialNumber: 153),
  MenuItem(id: 154, name: "Paneer Mirch Masala", price: 160, category: "PUNJABI", serialNumber: 154),
  MenuItem(id: 155, name: "Paneer Chana Masala", price: 160, category: "PUNJABI", serialNumber: 155),
  MenuItem(id: 156, name: "Lollipop Masala", price: 160, category: "PUNJABI", serialNumber: 156),
  MenuItem(id: 157, name: "Capsicum Masala", price: 150, category: "PUNJABI", serialNumber: 157),
  MenuItem(id: 158, name: "Veg. Hariyali", price: 140, category: "PUNJABI", serialNumber: 158),
  MenuItem(id: 159, name: "Veg. Hydrabadi", price: 140, category: "PUNJABI", serialNumber: 159),
  MenuItem(id: 160, name: "Veg. Adraki", price: 120, category: "PUNJABI", serialNumber: 160),
  MenuItem(id: 161, name: "Veg. Amrutsari", price: 160, category: "PUNJABI", serialNumber: 161),
  MenuItem(id: 162, name: "Veg. Dilli Darbar", price: 170, category: "PUNJABI", serialNumber: 162),
  MenuItem(id: 163, name: "Veg. Sabnam Curry", price: 170, category: "PUNJABI", serialNumber: 163),
  MenuItem(id: 164, name: "Veg. Divani Handi", price: 160, category: "PUNJABI", serialNumber: 164),
  MenuItem(id: 165, name: "Veg. Sabnam Kofta", price: 160, category: "PUNJABI", serialNumber: 165),
  MenuItem(id: 166, name: "Lajvab Kofta", price: 200, category: "PUNJABI", serialNumber: 166),
  MenuItem(id: 167, name: "Kaju Khoya", price: 180, category: "PUNJABI", serialNumber: 167),
  MenuItem(id: 168, name: "Veg. Tiranga", price: 220, category: "PUNJABI", serialNumber: 168),
  MenuItem(id: 169, name: "Mashroom Masala", price: 180, category: "PUNJABI", serialNumber: 169),
  MenuItem(id: 170, name: "Stuff Tometo", price: 140, category: "PUNJABI", serialNumber: 170),
  MenuItem(id: 171, name: "Dum Aloo", price: 140, category: "PUNJABI", serialNumber: 171),
  MenuItem(id: 172, name: "Dum Aloo Kashmiri", price: 150, category: "PUNJABI", serialNumber: 172),
  MenuItem(id: 173, name: "Jeera Aloo", price: 110, category: "PUNJABI", serialNumber: 173),
  MenuItem(id: 174, name: "Tometo Batata", price: 120, category: "PUNJABI", serialNumber: 174),
  MenuItem(id: 175, name: "Papad Roll Masala", price: 160, category: "PUNJABI", serialNumber: 175),
  MenuItem(id: 176, name: "Bengan Masala", price: 120, category: "PUNJABI", serialNumber: 176),
  MenuItem(id: 177, name: "Bengan Bhatta", price: 130, category: "PUNJABI", serialNumber: 177),
  MenuItem(id: 178, name: "Dal Fry", price: 100, category: "PUNJABI", serialNumber: 178),
  MenuItem(id: 179, name: "Butter Dal Fry", price: 130, category: "PUNJABI", serialNumber: 179),
  MenuItem(id: 180, name: "Dal Tadka", price: 130, category: "PUNJABI", serialNumber: 180),
  MenuItem(id: 181, name: "Palak Mutter", price: 120, category: "PUNJABI", serialNumber: 181),
  MenuItem(id: 182, name: "Aloo Palak", price: 120, category: "PUNJABI", serialNumber: 182),
  MenuItem(id: 183, name: "Chana Masala", price: 130, category: "PUNJABI", serialNumber: 183),
  MenuItem(id: 184, name: "Alu Gobi", price: 120, category: "PUNJABI", serialNumber: 184),
  MenuItem(id: 185, name: "Alu Mutter", price: 120, category: "PUNJABI", serialNumber: 185),
  MenuItem(id: 186, name: "Mix Veg.", price: 120, category: "PUNJABI", serialNumber: 186),
  MenuItem(id: 187, name: "Veg. Kolhapuri", price: 140, category: "PUNJABI", serialNumber: 187),
  MenuItem(id: 188, name: "Veg. Makhanwala", price: 150, category: "PUNJABI", serialNumber: 188),
  MenuItem(id: 189, name: "Veg. Jaypuri", price: 140, category: "PUNJABI", serialNumber: 189),
  MenuItem(id: 190, name: "Palak Masala", price: 120, category: "PUNJABI", serialNumber: 190),
  MenuItem(id: 191, name: "Bhindi Fry", price: 120, category: "PUNJABI", serialNumber: 191),

  // TANDOORI
  MenuItem(id: 192, name: "Tandoori Roti", price: 20, category: "TANDOORI", serialNumber: 192),
  MenuItem(id: 193, name: "Amul Butter Roti", price: 30, category: "TANDOORI", serialNumber: 193),
  MenuItem(id: 194, name: "Tava Amul Butter Roti", price: 25, category: "TANDOORI", serialNumber: 194),
  MenuItem(id: 195, name: "Butter Parotha", price: 50, category: "TANDOORI", serialNumber: 195),
  MenuItem(id: 196, name: "Sada Parotha", price: 40, category: "TANDOORI", serialNumber: 196),
  MenuItem(id: 197, name: "Butter Nan", price: 50, category: "TANDOORI", serialNumber: 197),
  MenuItem(id: 198, name: "Sada Nan", price: 40, category: "TANDOORI", serialNumber: 198),
  MenuItem(id: 199, name: "Kashmiri Nan", price: 70, category: "TANDOORI", serialNumber: 199),
  MenuItem(id: 200, name: "Masala Parotha", price: 70, category: "TANDOORI", serialNumber: 200),
  MenuItem(id: 201, name: "Stuff Parotha", price: 70, category: "TANDOORI", serialNumber: 201),
  MenuItem(id: 202, name: "Masala Kulcha", price: 70, category: "TANDOORI", serialNumber: 202),
  MenuItem(id: 203, name: "Sada Kulcha", price: 50, category: "TANDOORI", serialNumber: 203),
  MenuItem(id: 204, name: "Tava Roti", price: 15, category: "TANDOORI", serialNumber: 204),
  MenuItem(id: 205, name: "Tava Roti Butter", price: 20, category: "TANDOORI", serialNumber: 205),
  MenuItem(id: 206, name: "Paneer Parotha", price: 80, category: "TANDOORI", serialNumber: 206),
  MenuItem(id: 207, name: "Paneer Nan", price: 80, category: "TANDOORI", serialNumber: 207),
  MenuItem(id: 208, name: "Onion Nan", price: 60, category: "TANDOORI", serialNumber: 208),
  MenuItem(id: 209, name: "Cheese Nan", price: 90, category: "TANDOORI", serialNumber: 209),
  MenuItem(id: 210, name: "Garlic Nan", price: 70, category: "TANDOORI", serialNumber: 210),
  MenuItem(id: 211, name: "Garlic Chesses", price: 100, category: "TANDOORI", serialNumber: 211),

  // PAPAD, SALAD & SOUP
  MenuItem(id: 212, name: "Rosted Papad", price: 20, category: "PAPAD, SALAD & SOUP", serialNumber: 212),
  MenuItem(id: 213, name: "Fry Papad", price: 30, category: "PAPAD, SALAD & SOUP", serialNumber: 213),
  MenuItem(id: 214, name: "Masala Papad", price: 40, category: "PAPAD, SALAD & SOUP", serialNumber: 214),
  MenuItem(id: 215, name: "Butter Milk", price: 25, category: "PAPAD, SALAD & SOUP", serialNumber: 215),
  MenuItem(id: 216, name: "Green Salad", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 216),
  MenuItem(id: 217, name: "Finger Chips", price: 100, category: "PAPAD, SALAD & SOUP", serialNumber: 217),
  MenuItem(id: 218, name: "Tomato Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 218),
  MenuItem(id: 219, name: "Cream of Tomato Soup", price: 90, category: "PAPAD, SALAD & SOUP", serialNumber: 219),
  MenuItem(id: 220, name: "Hot & Sour Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 220),
  MenuItem(id: 221, name: "Veg. Manchow Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 221),
  MenuItem(id: 222, name: "Cream of Veg. Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 222),
  MenuItem(id: 223, name: "Sweet Corn Veg. Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 223),
  MenuItem(id: 224, name: "Sweet Corn Plain Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 224),
  MenuItem(id: 225, name: "Mushroom Soup", price: 90, category: "PAPAD, SALAD & SOUP", serialNumber: 225),
  MenuItem(id: 226, name: "Ministrone Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 226),
  MenuItem(id: 227, name: "Veg. Clear Soup", price: 70, category: "PAPAD, SALAD & SOUP", serialNumber: 227),
  MenuItem(id: 228, name: "Green Peas Soup", price: 70, category: "PAPAD, SALAD & SOUP", serialNumber: 228),
  MenuItem(id: 229, name: "Veg Noodles Soup", price: 80, category: "PAPAD, SALAD & SOUP", serialNumber: 229),
  MenuItem(id: 230, name: "Royal Veg. Soup", price: 90, category: "PAPAD, SALAD & SOUP", serialNumber: 230),
  MenuItem(id: 231, name: "Cocktail Soup", price: 90, category: "PAPAD, SALAD & SOUP", serialNumber: 231),

  // NOODLES
  MenuItem(id: 232, name: "Bombay Bhel", price: 150, category: "NOODLES", serialNumber: 232),
  MenuItem(id: 233, name: "Aaisi paisi Noodles", price: 170, category: "NOODLES", serialNumber: 233),
  MenuItem(id: 234, name: "Hakka Noodles", price: 150, category: "NOODLES", serialNumber: 234),
  MenuItem(id: 235, name: "Singapuri Noodles", price: 160, category: "NOODLES", serialNumber: 235),
  MenuItem(id: 236, name: "Veg. Rice & Noodles", price: 150, category: "NOODLES", serialNumber: 236),
  MenuItem(id: 237, name: "Schwan Noodles", price: 150, category: "NOODLES", serialNumber: 237),
  MenuItem(id: 238, name: "Fried Noodles", price: 170, category: "NOODLES", serialNumber: 238),
  MenuItem(id: 239, name: "Combination Noodles", price: 150, category: "NOODLES", serialNumber: 239),
  MenuItem(id: 240, name: "Mashroom Noodles", price: 160, category: "NOODLES", serialNumber: 240),
  MenuItem(id: 241, name: "Tripple's Schzwan Noodles", price: 200, category: "NOODLES", serialNumber: 241),
  MenuItem(id: 242, name: "American Chopsy", price: 160, category: "NOODLES", serialNumber: 242),
  MenuItem(id: 243, name: "Mashroom Chopsy", price: 170, category: "NOODLES", serialNumber: 243),
  MenuItem(id: 244, name: "Chinese Bhel", price: 150, category: "NOODLES", serialNumber: 244),
  MenuItem(id: 245, name: "Garlic Chawmin (liquid)", price: 160, category: "NOODLES", serialNumber: 245),
  MenuItem(id: 246, name: "Veg. Chawmin (liquid)", price: 150, category: "NOODLES", serialNumber: 246),
  MenuItem(id: 247, name: "Huanan Noodles", price: 200, category: "NOODLES", serialNumber: 247),

  // VEG. FOOD & GRAVY
  MenuItem(id: 248, name: "Paneer bullet", price: 220, category: "VEG. FOOD & GRAVY", serialNumber: 248),
  MenuItem(id: 249, name: "Paneer Schzwen Roll", price: 240, category: "VEG. FOOD & GRAVY", serialNumber: 249),
  MenuItem(id: 250, name: "Veg. Green Ball", price: 160, category: "VEG. FOOD & GRAVY", serialNumber: 250),
  MenuItem(id: 251, name: "Veg. Krivsi", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 251),
  MenuItem(id: 252, name: "Mashroom Roll", price: 220, category: "VEG. FOOD & GRAVY", serialNumber: 252),
  MenuItem(id: 253, name: "Veg. Manchurian (Liquid)", price: 160, category: "VEG. FOOD & GRAVY", serialNumber: 253),
  MenuItem(id: 254, name: "Veg. Manchurian (Dry)", price: 160, category: "VEG. FOOD & GRAVY", serialNumber: 254),
  MenuItem(id: 255, name: "Mashroom Manchurian (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 255),
  MenuItem(id: 256, name: "Baby Corn Manchurian (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 256),
  MenuItem(id: 257, name: "Baby Corn Manchurian (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 257),
  MenuItem(id: 258, name: "Baby Corn Chilli (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 258),
  MenuItem(id: 259, name: "Paneer Manchurian (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 259),
  MenuItem(id: 260, name: "Paneer Manchurian (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 260),
  MenuItem(id: 261, name: "Paneer Chilli (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 261),
  MenuItem(id: 262, name: "Paneer Chilli (Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 262),
  MenuItem(id: 263, name: "Paneer mamtal (Dry)", price: 250, category: "VEG. FOOD & GRAVY", serialNumber: 263),
  MenuItem(id: 264, name: "Paneer '65 (Dry)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 264),
  MenuItem(id: 265, name: "Paneer '65(Liquid)", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 265),
  MenuItem(id: 266, name: "Cocktail (Dry/Liquid)", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 266),
  MenuItem(id: 267, name: "Veg. Chilli (Dry)", price: 170, category: "VEG. FOOD & GRAVY", serialNumber: 267),
  MenuItem(id: 268, name: "Veg. Chilli (Liquid)", price: 170, category: "VEG. FOOD & GRAVY", serialNumber: 268),
  MenuItem(id: 269, name: "Veg. '65 (Dry)", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 269),
  MenuItem(id: 270, name: "Veg ' 65(Liquid)", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 270),
  MenuItem(id: 271, name: "Potato Chilli", price: 180, category: "VEG. FOOD & GRAVY", serialNumber: 271),
  MenuItem(id: 272, name: "Veg. Lollipop", price: 200, category: "VEG. FOOD & GRAVY", serialNumber: 272),

  // RICE DISH
  MenuItem(id: 273, name: "Huanan Rice", price: 200, category: "RICE DISH", serialNumber: 273),
  MenuItem(id: 274, name: "Hongkong Rice", price: 200, category: "RICE DISH", serialNumber: 274),
  MenuItem(id: 275, name: "Aahar Sp. Rice", price: 220, category: "RICE DISH", serialNumber: 275),
  MenuItem(id: 276, name: "Veg. Fried Rice", price: 150, category: "RICE DISH", serialNumber: 276),
  MenuItem(id: 277, name: "Mix Veg. Fried Rice", price: 150, category: "RICE DISH", serialNumber: 277),
  MenuItem(id: 278, name: "Veg. Ginger Fried Rice", price: 150, category: "RICE DISH", serialNumber: 278),
  MenuItem(id: 279, name: "Garlic Fried Rice", price: 170, category: "RICE DISH", serialNumber: 279),
  MenuItem(id: 280, name: "Combination Rice", price: 160, category: "RICE DISH", serialNumber: 280),
  MenuItem(id: 281, name: "Mashroom Fried Rice", price: 190, category: "RICE DISH", serialNumber: 281),
  MenuItem(id: 282, name: "Schezwan Fried Rice", price: 160, category: "RICE DISH", serialNumber: 282),
  MenuItem(id: 283, name: "Tripple Schezwan Rice", price: 200, category: "RICE DISH", serialNumber: 283),
  MenuItem(id: 284, name: "Singapoori Fried Rice", price: 160, category: "RICE DISH", serialNumber: 284),
  MenuItem(id: 285, name: "Chinese Veg. Pulao", price: 150, category: "RICE DISH", serialNumber: 285),
  MenuItem(id: 286, name: "Paneer Pulao", price: 200, category: "RICE DISH", serialNumber: 286),
  MenuItem(id: 287, name: "Cheese Pulao", price: 220, category: "RICE DISH", serialNumber: 287),
  MenuItem(id: 288, name: "Punjabi Veg. Pulao", price: 160, category: "RICE DISH", serialNumber: 288),
  MenuItem(id: 289, name: "Veg. Kashmiri Pulao", price: 180, category: "RICE DISH", serialNumber: 289),
  MenuItem(id: 290, name: "Green Peas Pulao", price: 150, category: "RICE DISH", serialNumber: 290),
  MenuItem(id: 291, name: "Veg. Biryani", price: 160, category: "RICE DISH", serialNumber: 291),
  MenuItem(id: 292, name: "Hydrabadi Biryani", price: 160, category: "RICE DISH", serialNumber: 292),
  MenuItem(id: 293, name: "Jira Rice", price: 110, category: "RICE DISH", serialNumber: 293),
  MenuItem(id: 294, name: "Plain Rice", price: 90, category: "RICE DISH", serialNumber: 294),
  MenuItem(id: 295, name: "Masala Rice", price: 160, category: "RICE DISH", serialNumber: 295),
  MenuItem(id: 296, name: "Half Jira Rice", price: 80, category: "RICE DISH", serialNumber: 296),
  MenuItem(id: 297, name: "Half Plain Rice", price: 70, category: "RICE DISH", serialNumber: 297),
  MenuItem(id: 298, name: "Half Masala Rice", price: 110, category: "RICE DISH", serialNumber: 298),
  MenuItem(id: 299, name: "Veg.Rayta", price: 80, category: "RICE DISH", serialNumber: 299),
  MenuItem(id: 300, name: "Kashmiri Rayta", price: 120, category: "RICE DISH", serialNumber: 300),
  MenuItem(id: 301, name: "Pineapple Rayta", price: 100, category: "RICE DISH", serialNumber: 301),
  MenuItem(id: 302, name: "Bundi Rayta", price: 90, category: "RICE DISH", serialNumber: 302),

  // SIZZLERS & COLD DRINKS
  MenuItem(id: 303, name: "Veg. Sizzlers", price: 250, category: "SIZZLERS & COLD DRINKS", serialNumber: 303),
  MenuItem(id: 304, name: "Mix Veg. Sizzlers", price: 250, category: "SIZZLERS & COLD DRINKS", serialNumber: 304),
  MenuItem(id: 305, name: "Combination Sizzlers", price: 250, category: "SIZZLERS & COLD DRINKS", serialNumber: 305),
  MenuItem(id: 306, name: "Mix Grill Sizzlers", price: 250, category: "SIZZLERS & COLD DRINKS", serialNumber: 306),
  MenuItem(id: 307, name: "Chinese Sizzlers", price: 250, category: "SIZZLERS & COLD DRINKS", serialNumber: 307),
  MenuItem(id: 308, name: "Garlic Ball (dry/liquid)", price: 160, category: "SIZZLERS & COLD DRINKS", serialNumber: 308),
  MenuItem(id: 309, name: "Ginjer Ball (dry/liquid)", price: 160, category: "SIZZLERS & COLD DRINKS", serialNumber: 309),
  MenuItem(id: 310, name: "Veg. Cheese Ball (dry)", price: 180, category: "SIZZLERS & COLD DRINKS", serialNumber: 310),
  MenuItem(id: 311, name: "Veg. Spring roll", price: 200, category: "SIZZLERS & COLD DRINKS", serialNumber: 311),
  MenuItem(id: 312, name: "Hara Bhara Kabab", price: 200, category: "SIZZLERS & COLD DRINKS", serialNumber: 312),
  MenuItem(id: 313, name: "Schzwan Ball (dry/liquid)", price: 170, category: "SIZZLERS & COLD DRINKS", serialNumber: 313),
  MenuItem(id: 314, name: "Soft Drink(300 ml.)", price: 40, category: "SIZZLERS & COLD DRINKS", serialNumber: 314),
  MenuItem(id: 315, name: "Soft Drink(1.5 Lit.)", price: 90, category: "SIZZLERS & COLD DRINKS", serialNumber: 315),
  MenuItem(id: 316, name: "Soft Drink(2 Lit.)", price: 110, category: "SIZZLERS & COLD DRINKS", serialNumber: 316),
  MenuItem(id: 317, name: "Soda", price: 20, category: "SIZZLERS & COLD DRINKS", serialNumber: 317),
  MenuItem(id: 318, name: "Min. Water", price: 20, category: "SIZZLERS & COLD DRINKS", serialNumber: 318),
];
